### ISSUE TITLE
GeoPandas might change CRS attribute in the future

### ISSUE THREAD

**Issue by jorisvandenbossche** [sentinel-hub/eo-learn#101]
@mlubej following your talk at GeoPython ;)

I noticed this pattern in the geometry subpackage that uses geopandas:

https://github.com/sentinel-hub/eo-learn/blob/d57fb48fe6924bc0cd7e65e7f7bfd8da6efa975d/geometry/eolearn/geometry/transformations.py#L127-L129

I wanted to give a heads up that we might be going to change the return value of the `crs` attribute to a `pyproj.CRS` object, and then such code will not work anymore.
See https://github.com/geopandas/geopandas/issues/1003 for a related issue.

Seeing how it is used here, we might need to think about backwards compatibility when doing such a change, but not sure how that could be achieved.

**Comment by mlubej** [comment]
Hi @jorisvandenbossche!

> @mlubej following your talk at GeoPython ;)

Stalker!

On a more serious note, thanks a lot for the heads up, we will definitely be on the lookout for the changes and implement them as soon as possible. Don't worry about the backwards compatibility because of us.

Cheers!

**Comment by vatsalag99** [comment]
This change has occurred. I am currently unable to convert my shapefile to a raster (`VectorToRaster`) and found that this was the error: 

`TypeError: During execution of task VectorToRaster: argument of type 'CRS' is not iterable
`
Please let me know how I should proceed.

**Comment by batic** [comment]
Hi,

We are aware of this issue, but didn’t yet have the time to address it properly. For the moment, you can downgrade geopandas to 0.6.x.

Sorry for the inconvenience.

**Comment by AleksMat** [comment]
This has now been fixed in `eo-learn` version `0.7.3`. It now works both with `geopandas==0.7.0` and with older `geopandas` versions.

Closing the issue.
