### ISSUE TITLE
Problem using ImportFromTiff - folder argument seems to require file

### ISSUE THREAD

**Issue by pmallas** [sentinel-hub/eo-learn#106]
I am new to eo-learn and I am trying to use the ImportFromTiff ingest feature. I constructed a very simple work flow with just ImportFromTiff and a directory of 12 small tiff patches of the same area.

The doc  (https://eo-learn.readthedocs.io/en/latest/eolearn.io.local_io.html#eolearn.io.local_io.ImportFromTiff) seems to imply that by using the folder option, all image files in the folder will be ingested.  But I get a Rasterio: Permission denied error.  Which is caused by the fact that rasterio is using the ImportFromTiff folder argument and trying to open it as a file.  

I don't know if this is a bug or if I am not using the ImportFromTiff as intended.  Regards, Paul

Python code:
>tiff_dir = 'd:\\tiffs'
>input_task = ImportFromTiff((FeatureType.DATA_TIMELESS, 'SAR_bands'), tiff_dir)
>workflow = EOWorkflow.make_linear_workflow(input_task)
>result = workflow.execute()

Error:
~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Method 'make_linear_workflow' will soon be removed. Use LinearWorkflow class instead
  """
---------------------------------------------------------------------------
RasterioIOError                           Traceback (most recent call last)
<ipython-input-5-8f5d7db25e47> in <module>
      5 workflow = EOWorkflow.make_linear_workflow(input_task)
      6 
----> 7 result = workflow.execute()

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\eolearn\core\eoworkflow.py in execute(self, input_args, monitor)
    164         input_args = self.parse_input_args(input_args)
    165 
--> 166         _, intermediate_results = self._execute_tasks(input_args=input_args, out_degs=out_degs, monitor=monitor)
    167 
    168         return WorkflowResults(intermediate_results)

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\eolearn\core\eoworkflow.py in _execute_tasks(self, input_args, out_degs, monitor)
    203                                         input_args=input_args,
    204                                         intermediate_results=intermediate_results,
--> 205                                         monitor=monitor)
    206 
    207             intermediate_results[dep] = result

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\eolearn\core\eoworkflow.py in _execute_task(self, dependency, input_args, intermediate_results, monitor)
    236 
    237         LOGGER.debug("Computing %s(*%s, **%s)", task.__class__.__name__, str(inputs), str(kw_inputs))
--> 238         return task(*inputs, **kw_inputs, monitor=monitor)
    239 
    240     def _relax_dependencies(self, *, dependency, out_degrees, intermediate_results):

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\eolearn\core\eotask.py in __call__(self, monitor, *eopatches, **kwargs)
     49         #     return self.execute_and_monitor(*eopatches, **kwargs)
     50 
---> 51         return self._execute_handling(*eopatches, **kwargs)
     52 
     53     def execute_and_monitor(self, *eopatches, **kwargs):

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\eolearn\core\eotask.py in _execute_handling(self, *eopatches, **kwargs)
     70             exception, traceback = caught_exception
     71             raise type(exception)('During execution of task {}: {}'.format(self.__class__.__name__,
---> 72                                                                            exception)).with_traceback(traceback)
     73 
     74         self.private_task_config.end_time = datetime.datetime.now()

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\eolearn\core\eotask.py in _execute_handling(self, *eopatches, **kwargs)
     63         caught_exception = None
     64         try:
---> 65             return_value = self.execute(*eopatches, **kwargs)
     66         except BaseException as exception:
     67             caught_exception = exception, sys.exc_info()[2]

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\eolearn\io\local_io.py in execute(self, eopatch, filename)
    254             eopatch = EOPatch()
    255 
--> 256         with rasterio.open(self._get_file_path(filename)) as source:
    257 
    258             data_bbox = BBox(source.bounds, CRS(source.crs.to_epsg()))

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\rasterio\env.py in wrapper(*args, **kwds)
    421 
    422         with env_ctor(session=session):
--> 423             return f(*args, **kwds)
    424 
    425     return wrapper

~\AppData\Local\Continuum\anaconda3\envs\csRaster\lib\site-packages\rasterio\__init__.py in open(fp, mode, driver, width, height, count, crs, transform, dtype, nodata, sharing, **kwargs)
    214         # None.
    215         if mode == 'r':
--> 216             s = DatasetReader(path, driver=driver, **kwargs)
    217         elif mode == 'r+':
    218             s = get_writer_for_path(path)(path, mode, driver=driver, **kwargs)

rasterio\_base.pyx in rasterio._base.DatasetBase.__init__()

RasterioIOError: During execution of task ImportFromTiff: d:\tiffs: Permission denied

**Comment by devisperessutti** [comment]
Hi @pmallas 

Both options (read files from specified folder or single file) are supported. If all patches will import data from a single tiff file, it is recommended to initialise the task with `folder=path_to_tiff_file`, such that no other argument is needed. If instead each eopatch will import data from different tiff files that are stored in the same folder, then the task is initialised with `folder=path_to_dir`, and the argument `filename=filename_of_tiff` need to be provided at run time to the execute method. When using `EOWorkflow`, a list of dictionaries with such filenames need to be provided.

In your case, this should work

```python
tiff_dir = 'd:\tiffs'
input_task = ImportFromTiff((FeatureType.DATA_TIMELESS, 'SAR_bands'), tiff_dir)
result = input_task.execute(filename='filename.tiff')
```

**Comment by pmallas** [comment]
Hi @devisperessutti  - thanks for your reply.

Yes, the above code works for me.  I guess the documentation threw me a little bit here:
   _filename – filename of tiff file or None if entire path has already been specified in folder parameter_

**Comment by pmallas** [comment]
@devisperessutti - you state:
_ When using EOWorkflow, a list of dictionaries with such filenames need to be provided._

How should this list of dictionaries look?  I have tried what I thought you were describing, but I I am not having success with multiple files.  I have tried 

workflow = EOWorkflow.make_linear_workflow(input_task)

result = workflow.execute({input_task:  [{'filename': 'S1A_IW_GRDH_1SDV_20190508T110621.tif'}, 
                                        {'filename': 'S1A_IW_GRDH_1SDV.tif'}, 
                                        {'filename': 'S1A_IW_GRDH_1SDV.tif'}]})

And a few other things, but nothing I have done works.

Thanks again.

**Comment by devisperessutti** [comment]
More details on the calls using `EOWorkflow` and `EOExecutor` are available on cells 17 and 18 [here](https://eo-learn.readthedocs.io/en/latest/examples/core/CoreOverview.html#EOWorkflow). I actually wrote a misleading sentence. Using the workflow, one dictionary is provided, while using the executor you can provide the list of dictionaries. Each element of the list needs to include the tasks needing dynamic arguments along with the arguments themselves. 

Please try the following to run on a single eopatch

```python
workflow = EOWorkflow.make_linear_workflow(input_task)

result = workflow.execute({input_task: {'filename': 'S1A_IW_GRDH_1SDV_20190508T110621.tif'}})
``` 

and this to run on multiple eopatches (in parallel)

```python
from eolearn.core import EOExecutor

workflow = EOWorkflow.make_linear_workflow(input_task)

execution_args = [{input_task: {'filename': 'S1A_IW_GRDH_1SDV_20190508T110621.tif'}},
{input_task: {'filename': 'S1A_IW_GRDH_1SDV.tif'}},
{input_task: {'filename': 'S1A_IW_GRDH_1SDV.tif'}}]


executor = EOExecutor(workflow, execution_args, save_logs=True, logs_folder='.')

executor.run(workers=3)  # The execution will use at most 3 parallel processes
```

**Comment by pmallas** [comment]
Excellent - thank you.
