### ISSUE TITLE
Segementation error

### ISSUE THREAD

**Issue by YaswinTeja** [sentinel-hub/eo-learn#122]
Hi ,  
I have installed eo-learn on Mac (python 3.7). I am trying to import the below command and its showing below error. 

Exit from Python after run the below command 
from eolearn.core import EOPatch, FeatureType
Segmentation fault: 11

Successfully built eo-learn eo-learn-core eo-learn-coregistration eo-learn-features eo-learn-geometry eo-learn-io eo-learn-mask eo-learn-ml-tools eo-learn-visualization
Installing collected packages: eo-learn-core, eo-learn-coregistration, eo-learn-features, eo-learn-geometry, eo-learn-io, eo-learn-mask, eo-learn-ml-tools, eo-learn-visualization, eo-learn
Successfully installed eo-learn-0.5.2 eo-learn-core-0.5.2 eo-learn-coregistration-0.5.0 eo-learn-features-0.5.0 eo-learn-geometry-0.5.0 eo-learn-io-0.5.0 eo-learn-mask-0.5.0 eo-learn-ml-tools-0.5.0 eo-learn-visualization-0.5.2

**Comment by devisperessutti** [comment]
Hi,

We'd need more information about the set-up of your OS and Python environment to help you pin-point the problem.
