### ISSUE TITLE
Spatio-Temporal Feature extraction task hanging at interpolation

### ISSUE THREAD

**Issue by bibblybobbly** [sentinel-hub/eo-learn#124]
Hi,

I have been trying to run the Spatio-Temporal Feature extraction task example notebook locally, and have success until I reach box 21 and specifically the line:

`result_with_interp = workflow_with_interp.execute({load:{'eopatch_folder':'eopatch'}})`

It seems to hang here indefinitely. Could you provide any advice here please? 
Many thanks

**Comment by devisperessutti** [comment]
Hi,

We have [submitted improvements](https://github.com/sentinel-hub/eo-learn/pull/159) to the example to use `CubicInterpolation` instead of spline, speeding up execution.

Thanks for reporting

**Comment by devisperessutti** [comment]
This is now fixed with latest release.
