### ISSUE TITLE
Urban Management Research Application

### ISSUE THREAD

**Issue by toniesteves** [sentinel-hub/eo-learn#145]
Hello! I need to write a paper about LULC and Urban Management and I would like to know if there is some kind of free account in sentinel hub? If not maybe another way to integrate eo-learn with sentinel-2 data.

**Comment by gmilcinski** [comment]
You can create a free 30 days trial account with just your e-mail:    
http://www.sentinel-hub.com/create_account  
If you require something more extensive, please check this FAQ:  
https://www.sentinel-hub.com/faq/it-possible-get-free-account-research-purposes
