### ISSUE TITLE
ExportToTiff issue

### ISSUE THREAD

**Issue by MarkFizzel** [sentinel-hub/eo-learn#147]
Hi eo-learn team,

I had the pleasure of attending your course at Nordic Remote Sensing Conference and now I am trying to build my own workflow.

Currently my workflow consists of downloading, saving, then loading the saved eopatch and then Exporting to geotiff. 

When running the workflow I get a ValueError.
e.g. this line ‘exporter = ExportToTiff(eopatch.data['TRUE-COLOR-S2-L1C'])’
returns the following error:
ValueError: Unknown format of input features: [[[[0.28975    0.356      0.26525   ]
   [0.29       0.35375    0.26225   ]
   [0.287      0.3585     0.2625    ]
   ...
   [0.20325    0.2685     0.264     ]
   [0.19675    0.2565     0.25825   ]
   [0.188      0.25225    0.25175   ]]

If I print eopatch:
‘EOPatch(
  data: {
    TRUE-COLOR-S2-L1C: numpy.ndarray(shape=(32, 1007, 1002, 3), dtype=float32)’
Etc.

Is the a example of how to save a eopatch or part of one to a geotiff?

Best regards.
  Mark Falkenberg (sdfe.dk)

**Comment by devisperessutti** [comment]
Hi Mark!

Please check the signature of the [`ExportToTiff`](https://eo-learn.readthedocs.io/en/latest/eolearn.io.local_io.html#eolearn.io.local_io.ExportToTiff) task. You need to provide the format of the data, e.g. `image_dtype=np.float32`.

Additionally, you need to provide the time index or band index if you want to export only specific times/bands. I would recommend exporting a specific band and time index first, to check the task works, and then add bands/time indices. Please check the order of the exported bands, as specified in the documentation.

Hope this helps,
Devis
