### ISSUE TITLE
EOExecutor - make report makes kernel to dead

### ISSUE THREAD

**Issue by christianayala10** [sentinel-hub/eo-learn#15]
When I try to make executor report my notebook's kernel deads. I'm following the documentation examples showed [here](https://eo-learn.readthedocs.io/en/latest/examples/eolearn-core-overview.html#EOExecutor).

I don't know why this is happening. I'm working with python 3.6  with: 

eo-learn-core v0.3.1
eo-learn-coregistration v0.3.0
eo-learn-features v0.3.1
eo-learn-geometry v0.3.1
eo-learn-io v0.3.1
eo-learn-mask v0.3.1
eo-learn-ml-tools v0.3.0
Fiona v1.7.11
rasterio v0.36.0

**Comment by devisperessutti** [comment]
Hello,

Can you please specify which error you get when running the notebook?

Also, is the folder `eoexecution-report-*` and the `execution-*.log` files generated correctly?

**Comment by devisperessutti** [comment]
The latest released version 0.3.2 fixes an issue in the executor, that might have been the cause of the error. 

Please test the new version and report if issue is persisting.

**Comment by christianayala10** [comment]
Hi Devis,

I have upgraded to the new version and the error continues. Maybie it is
due to the fact that I'm currently working on GPU instead of CPU as my
college does whose kernel doesn't die.

I have another question: Which of the following workflows you can execute
by using an EoExecutor and which can't?

[image: image.png]

Thank you in advance,

Christian.

**Comment by devisperessutti** [comment]
Hi Christian,

I cannot see which workflows you mean (no image attached), but the executor should work with any workflow you specify.

Can you report which error you are getting? 

Devis

**Comment by christianayala10** [comment]
There is a image in the email body. I will try to explain it ti you:

I have those tasks: A,B,C wich dependencies are: A-C, B->C.

Is this posible? Can I make a workflow with two inputs that ends in the
same thask? How their behaviour is? A and B waits each other yo be
completed before start with C?

(In the image there are more situations but this is the one that I need
most)

**Comment by devisperessutti** [comment]
Yes it is possible. You can have a workflow with multiple inputs and multiple outputs. 

The only constrain is that the graph you are building is not cyclic.

Please have a look at this toy [example](https://github.com/sentinel-hub/eo-learn/blob/master/examples/core/BasicWorkflows.ipynb) where three input tasks are combined to create an algebraic operation.

Hope this helps.
