### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by zhouhaodong2019** [sentinel-hub/eo-learn#168]
Hello eo-learn team,

I'm a beginner.
when i download data from sentinel-hub ，It's always reported as a Error like this:

Server response: "found non-noded intersection between LINESTRING ( -673238.5054573906 9254393.926590187, -1.0101222836776022E7 -2.074846824889552E7 ) and LINESTRING ( -2.1329354216789323E8 -8.011576911120571E7, -3674691.709750813 -7121193.918430386 ) [ (-6082516.570426663, -7959659.31626794, NaN) ]"

**Comment by gmilcinski** [comment]
I'd say the geometry you provide is not correct. It is unfortunately not possible to debug anything from the information you have provided. 
Please share the OGC WCS call (masking instance ID) and we will take a look into it

**Comment by zhouhaodong2019** [comment]
when i run the demo(How To: Land-Use-Land-Cover Prediction for Slovenia),i can download the data.
but when i use other geojson file，i can't do it
[SZ.txt](https://github.com/sentinel-hub/eo-learn/files/3993589/SZ.txt)

**Comment by mlubej** [comment]
Hi @zhouhaodong2019 ,

usually this is a problem of changing the geometry of the area of interest without changing the CRS. If you are using a UTM CRS, you should provide the geometry in natural UTM CRS of your area.
