### ISSUE TITLE
Can we give exact polygon/geojson to get the area of interest using BBOX?

### ISSUE THREAD

**Issue by palaiya** [sentinel-hub/eo-learn#174]
As BBOX parameter in WMS/WCS request takes top-left and bottom-right of the bounding box separated by commas. Is there a way we can give exact polygon/geojson to load the data in EO Patch.

Moreover, I am new to eo-learn. I have this basic question doing WMS/WCS request like this 

```
download_task = S2L1CWCSInput(layer=layer, 
                           resx='20m', resy='20m', 
                           maxcc=.3) 
```
and then piping it to workflow and finally executing it. Does this download the area of interest in Data folder in `.npy` format and cache it for further local processing? `.npy` is used here for faster processing, right?

**Comment by palaiya** [comment]
@devisperessutti any idea about this?

**Comment by devisperessutti** [comment]
Hi @palaiya,

The `BBox` needs to define a rectangular region for which you will get data. Given a polygon, you can create a `BBox` by using the `polygon.bounds`. 

The task returns numpy arrays which are stored in memory until they are saved (as `.npy` or `.npy.gz`) on disk using the `EOPatch().save` or `SaveTask`.

**Comment by palaiya** [comment]
I thought of doing in the following manner. Creating a `geojson` of my polygon named as `area_geojson` and then calculating the bounds as you mentioned w.r.t `area_crs`.  This should work right?

```
def calculate_bound_and_box(area_geojson, area_crs):
    area = gpd.read_file(area_geojson)
    area = area.to_crs(crs={'init': CRS.ogc_string(area_crs)})
    area_shape = area.geometry.to_numpy()[-1]
    return BBox(bbox=[area_shape.bounds[0], area_shape.bounds[1], area_shape.bounds[2], area_shape.bounds[3]], crs=area_crs)
```

**Comment by devisperessutti** [comment]
yes, `return BBox(bbox=area_shape.bounds, crs=area_crs)` should also work
