### ISSUE TITLE
SI_LULC_pipeline example throws Attribute Error 

### ISSUE THREAD

**Issue by palaiya** [sentinel-hub/eo-learn#176]
I was trying to execute the SI_LULC_pipeline example. And the following line throws the

**Exception:**
`AttributeError: 'GeometryArray' object has no attribute 'tolist'`

**Code:**
`country_shape = country.geometry.values.tolist()[-1]`

**Comment by AleksMat** [comment]
This has now been updated and pushed to `master` branch. Thanks for reporting the problem. :+1:
