### ISSUE TITLE
The eodata_io does not work with lazy loading.

### ISSUE THREAD

**Issue by bsircelj** [sentinel-hub/eo-learn#180]
The method `save_eopatch` in `eodata_io.py` removes whole patch regardless if it was lazy loaded on line 32: `filesystem.removetree(patch_location)` thus producing an error when the patch is later tried to be saved:
`fs.errors.ResourceNotFound: resource 'During execution of task SaveTask: resource '/eopatch/data/NDVI.npy' not found' not found`

**Comment by mlubej** [comment]
@AleksMat should we just make a try/except here with a `ResourceNotFound` exception? This would mean that the lazy-loaded feature would get skipped and would not be present on the disk.

I believe that if you lazy load and overwrite patch, it should not matter that you delete the features which were lazy-loaded. If you really care about the existing features, then you should use the overwrite features permission. 

On the other hand, if you care about such features, one could make sure that the eopatch is fully loaded into memory before the `removetree` is executed, but that brings potential overhead.

**Comment by zigaLuksic** [comment]
This has been fixed in version `0.10`
