### ISSUE TITLE
High memory usage when downloading data for EOPatches

### ISSUE THREAD

**Issue by JanChytry** [sentinel-hub/eo-learn#183]
Hey all, 

firstly big thanks for EO Learn, it is an amazing thing you've done.

I run eo learn in a Jupyter Notebook on a server with extensible computational resources and even though I am currently facing a memory usage problem when downloading time series (one full year) of images and other auxiliary data for EOpatches. 
Although my AOI was set quite small, downloading allocates as much memory as it goes and, at the memory overflow, it kills the kernel. 
Why is that happening? Is there any way to set up memory usage limit so it is held in mantinels? Firstly, the server was set to 8 GB, later we upscaled it to 16 GB to no improvement.  

Thanks a lot and regards!

PS: Sorry if this is a solved thing, I am a beginner in the field.

**Comment by Rim-chan** [comment]
I had the same problem, when I tried to retrieve the FEATURES google collab kept crashing and the RAM instantly hits its limits. What I did was that, I sliced FEATURES and loaded each slice separately and stored it in an hdf file. It's time-consuming, but it works, I was able to load the entire data later on.

**Comment by mlubej** [comment]
Hi @JanChytry and @Rim-chan,

If the areas of interest are small, then perhaps you are computing too many eopatches at once, where a lot of copying and loading in RAM is happening at the same time. Try reducing the number of parallel processes, then the RAM usage should drop significantly.

Perhaps the defaults settings of the notebook are too extreme for an everyday setup and the number of processes should be decreased...

**Comment by Rim-chan** [comment]
Thanks for the quick response, but for me, the issue arise when I try to load the FEATURES after I concatenate, apply cloud masks, interpolation, and resampling, which is odd because my AOI is really small.

**Comment by Rim-chan** [comment]
Thanks for the response !
I deleted the code from my notebook, as I was trying to figure things out and. But I posted the issue on StackExchange with the code and screen shots. Here is the link:
[https://gis.stackexchange.com/questions/364640/problem-with-sentinel-2-l2a-cloud-mask-and-valid-pixel-counts](url)

**Comment by mlubej** [comment]
Could you perhaps provide an example notebook or something similar, so I can check for myself? A small area and a year or two of data shouldn't cause any problems.

**Comment by Rim-chan** [comment]
Sure, do you think I can do that via email?

**Comment by mlubej** [comment]
> Sure, do you think I can do that via email?

Of course. You can either zip it and drop it here, send it via some cloud service, or send an email to [me](mailto:matic.lubej@sinergise.com).

**Comment by mlubej** [comment]
Dear @Rim-chan,

I checked your notebooks and already discussed with you in private. My conclusion is that the amount of data that you are loading is in fact too large, due to the sheer nature of data. 

Splitting the area into patches is used to ease up the usage of RAM, but when you prepare the data for training, you load everything up into the memory. My suggestion would be to decrease the number of spatially sampled pixels (currently default in the notebook is 125000). This way, the full sampled data will be smaller and perhaps more suitable for your environment.

On the other hand, if you manage to make it work with some other tools, then all the better.

Hope this helped.

Cheers!

**Comment by Rim-chan** [comment]
Thanks for the help Matic ! I'll try to use fewer samples and see what happens.

**Comment by mlubej** [comment]
No problem!
