### ISSUE TITLE
TRUE-COLOR-S2-L1C layer configuration

### ISSUE THREAD

**Issue by fvivian** [sentinel-hub/eo-learn#2]
I was trying to run the example land-cover-map over Switzerland on my local machine but ran into a problem:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-54b437ee3056> in <module>()
      8 results = workflow.execute({input_task:{'bbox':bbox, 'time_interval':time_interval},
      9                             export_val_sh:{'filename':f'CH_data/valid_count-L1C/{tiff_name}'},
---> 10                             save:{'eopatch_folder':patch_name}
     11                            })

~\Anaconda3\lib\site-packages\eolearn\core\eoworkflow.py in execute(self, input_args)
    280         input_args = {WorkflowResult.get_key(k): v for k, v in input_args.items()} if input_args else {}
    281 
--> 282         _, intermediate_results = self._execute_tasks(input_args=input_args, outdegs=outdegs)
    283 
    284         return WorkflowResult(intermediate_results)

~\Anaconda3\lib\site-packages\eolearn\core\eoworkflow.py in _execute_tasks(self, input_args, outdegs)
    303             result = self._execute_task(input_args=input_args,
    304                                         intermediate_results=intermediate_results,
--> 305                                         task_id=t_id)
    306 
    307             intermediate_results[t_id] = result

~\Anaconda3\lib\site-packages\eolearn\core\eoworkflow.py in _execute_task(self, input_args, intermediate_results, task_id)
    331         inputs = tuple(intermediate_results[t_dep] for t_dep in self.deps[task_id])
    332         LOGGER.debug("Computing %s(*%s, **%s)", str(task), str(inputs), str(kw_inputs))
--> 333         return task(*inputs, **kw_inputs)
    334 
    335     def _relax_dependencies(self, *, intermediate_results, out_degrees, current_task_id):

~\Anaconda3\lib\site-packages\eolearn\core\eotask.py in __call__(self, *eopatches, **kwargs)
     39 
     40     def __call__(self, *eopatches, **kwargs):
---> 41         return self.execute(*eopatches, **kwargs)
     42 
     43 

~\Anaconda3\lib\site-packages\eolearn\mask\cloud_mask.py in execute(self, eopatch)
    246         # Raise error if last channel dimension is less than required
    247         if new_data.shape[-1] < len(self.classifier.band_idxs):
--> 248             raise ValueError("Data field has less than the required 10 bands")
    249 
    250         # Compute cloud mask and add as feature to EOPatch

ValueError: Data field has less than the required 10 bands
```
This message was shown when running the cell `[20]` in eo-learn/examples/land-cover-map/2_eopatch-L1C.ipynb with some minor tweaks.

Now I know it might be an issue due to my own adaptation to the region of Switzerland. So I would like to try run the notebook exactly as shown in this repository. Therefore I need to set up the layer in the configuartor. What is the specification of the TRUE-COLOR-S2-L1C layer you mention in the 2_eopatch-L1C.ipynb?

**Comment by azupanc** [comment]
Thanks for pointing it out. I've added a README (https://github.com/sentinel-hub/eo-learn/tree/master/examples) where instructions on how to add new configuration to your SH account using a predefined template that has all layers used in the examples are given -- including the TRUE-COLOR-S2-L1C and BANDS-S2CLOUDLESS. 

Based on your error I assume you have changed the layer name in the following line
```
add_clm = AddCloudMaskTask(cloud_classifier, 
                           'BANDS-S2CLOUDLESS', 
                           cm_size_y='160m', 
                           cm_size_x='160m', 
                           cmask_field='CLM',
                           cprobs_field='CLP',
                           instance_id=INSTANCE_ID)
```
If you did, I suggest you to change it back to BANDS-S2CLOUDLESS, since the cloud detector needs the 10 bands in order to make the cloud classification.

**Comment by fvivian** [comment]
Thank you very much, this helped to actually be able to use your notebooks for testing. Unfortunately, now I get the following error from the same cell:
```
DownloadFailedException: Failed to download with HTTPError:
400 Client Error: Bad Request for url: https://services.sentinel-hub.com/ogc/wcs/0f6c0cd7-002d-4460-8017-4d78502d7d35?SERVICE=wcs&BBOX=370230.5261411405%2C5085303.344972428%2C380225.31836121203%2C5095400.767924464&FORMAT=image%2Ftiff%3Bdepth%3D32f&CRS=EPSG%3A32633&RESX=160m&RESY=160m&COVERAGE=TRUE_COLOR&REQUEST=GetCoverage&TIME=2017-01-01T10%3A04%3A07%2F2017-01-01T10%3A04%3A07&MAXCC=80.0&ShowLogo=False&Transparent=False&EvalScript=cmV0dXJuIFtCMDEsQjAyLEIwNCxCMDUsQjA4LEI4QSxCMDksQjEwLEIxMSxCMTJd
Server response: "Layer TRUE_COLOR not found"
```
I did not change the notebooks in any way, so I am sure to use the proper version. Now I don't know why it asks for the TRUE_COLOR layer, since the layers specified are TRUE-COLOR-S2-L1C and BANDS-S2CLOUDLESS. The configuration is as explained in the README.

If it is of any help: The error occured after the cell was running for several minutes. Network traffic was on full load, so I guess it was actually downloading some data.

**Comment by azupanc** [comment]
OK, I see now where the problem is. The AddCloudMaskTask actually doesn't create a SentinelHub request using the 'BANDS-S2CLOUDLESS' layer but does this by using eval script (simple script that returns the 10 necessary bands). Unfortunately, the OGC standard requires the LAYER parameter always to be specified although it has no impact on what kind of data is returned (10 bands in this case). The AddCloudMaskTask at the moment sets the layer to 'TRUE_COLOR' when it makes the request (the layer name is hardocded). If this layer doesn't exist then the above error is issued. 

This clearly needs to be fixed in the AddCloudMaskTask, but until then please use the updated version of example notebook. The issue can be circumvented by downloading the 10 bands in another task. If the data is already available the cloud detector doesn't download the data again.

**Comment by azupanc** [comment]
@fvivian the issue should be solved now. Please update your version of eo-learn and run the examples again.

**Comment by fvivian** [comment]
Thank you for the explanation and quick fix. The example runs without any issues now.

**Comment by nilshempelmann** [comment]
@fvivian  Sorry for opening the issue again. 
There is still/again a :
`Server response: "Layer BANDS-S2-L1C not found"`

Was running [your notebook ](https://github.com/sentinel-hub/eo-learn/blob/master/examples/io/SentinelHubIO.ipynb)

Is therer a way to query the Layer names?

**Comment by devisperessutti** [comment]
Hi @nilshempelmann 

Make sure the layer configuration is set up properly as for these [requirements](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html#Requirements). 

Login to the [Sentinel Hub configurator](https://services.sentinel-hub.com/oauth/auth) and add a new configuration using the Python scripts template. Then update your instance ID and the script should run.

**Comment by nilshempelmann** [comment]
Got it. Thanks !
