### ISSUE TITLE
Mask Eopatches according to polygon

### ISSUE THREAD

**Issue by Arraystud** [sentinel-hub/eo-learn#201]
I have multiple eopatches created based on a river shapefile. Currently I am trying to mask these patches according to the shapefile so that if: pixels of the eopatch are located within the river they still contain the information and ifelse: 0 or no information. Is this possible?

**Comment by devisperessutti** [comment]
Yes, this is possible using the [`VectorToRaster` task](https://eo-learn.readthedocs.io/en/latest/eolearn.geometry.transformations.html#eolearn.geometry.transformations.VectorToRaster), where for each eopatch you can burn your river vector data into a binary mask to be used to filter data.
