### ISSUE TITLE
Visualization process

### ISSUE THREAD

**Issue by Rim-chan** [sentinel-hub/eo-learn#206]
Hey, I am trying to follow your code and I was wondering how were you able to get the Indexes for arranging the grid tiles. When displaying my satellite images, temporal mean NDVI, and average cloud probability, the patches were randomly placed in the grid.

**Comment by mlubej** [comment]
Hi @Rim-chan! 

Indeed, in default the way the notebook is set up, the initial bboxes are not in an appropriate order to just stitch together. In the notebook that you are following,  the initial ordered `patchIDs` list was augmented by the following code
```python
patchIDs = np.transpose(np.fliplr(np.array(patchIDs).reshape(5, 5))).ravel()
```
which put the bboxes in the appropriate order for plotting.

**Comment by Rim-chan** [comment]
@mlubej thanks for the response! 
One more question, does this need to be executed before downloading the data?

**Comment by mlubej** [comment]
Hi @Rim-chan,

the augmented order is only used for `matplotlib` plotting, so it shouldn't affect the download :)

You can see this by the fact that `patchIDs` are only used when plotting the imagery, i.e.
```python
for i in tqdm(range(len(patchIDs))):
    eopatch = EOPatch.load(f'{path_out}/eopatch_{i}', lazy_loading=True)
    ...
```
