### ISSUE TITLE
svn_buffered.geojson missing in example_data

### ISSUE THREAD

**Issue by fatal69100** [sentinel-hub/eo-learn#207]
**_svn_buffered.geojson_** is missing in _examples/land-cover-map/extra_example-split_AOI.ipynb_

**Comment by mlubej** [comment]
Sorry about that. The buffer was removed from the example data and the examples weren't updated. The new file [svn_border.geojson](https://github.com/sentinel-hub/eo-learn/blob/master/example_data/svn_border.geojson) was introduced. Please try with that one, we'll update the examples at the earliest convenience.

Thank you for pointing this out!

**Comment by fatal69100** [comment]
You're welcome, I try to understand examples to get handly with the framework. Is the best way to pointing issues out is to propose a pull request ?

**Comment by mlubej** [comment]
If you find some inconsistencies, it's best if you create an issue like this. However, if you go through the examples and potentially find and fix some issues, we would be grateful if you prepare a PR with the fixed example notebooks!
