### ISSUE TITLE
True Division Error [invalid value encountered in true_divide]

### ISSUE THREAD

**Issue by sam99dave** [sentinel-hub/eo-learn#212]
/opt/venv/lib/python3.7/site-packages/eolearn/features/bands_extraction.py:86: RuntimeWarning: invalid value encountered in true_divide

ndi = (band_a - band_b + self.acorvi_constant) / (band_a + band_b + self.acorvi_constant)

band_a & band_b are being valued 0. It seems that the band data is not being fetched properly. 

Any solution to this will be great!!

**Comment by batic** [comment]
Hi @sam99dave,

Did you check if IS_DATA is valid where you want to calculate the index?

Otherwise, please share some more info (bbox, dates, data you are fetching and using. ...)

**Comment by mlubej** [comment]
Hi @sam99dave,

sometimes patches are on the borders of the satellite swath, so the values there can be `0` or `NaN`. If this happens, the `NDI` calculation will produce a warning (not an error), but the calculation should go through. If those values are invalid due to the values being outside of the satellite swath, then you  can filter them out by using the `IS_DATA` flag, as suggested by @batic.

**Comment by sam99dave** [comment]
> Hi @sam99dave,
> 
> sometimes patches are outside the border of the satellite swath, so the values there can be `0` or `NaN`. If this happens, the `NDI` calculation will produce a warning (not an error), but the calculation should go through. If those values are invalid due to the values being outside of the satellite swath, then you can filter them out by using the `IS_DATA` flag, as suggested by @batic.

**Comment by sam99dave** [comment]
I was just trying to run the SI_LULC_pipeline.ipynb file. Exact with the same details nothing changed

**Comment by mlubej** [comment]
> I was just trying to run the SI_LULC_pipeline.ipynb file. Exact with the same details nothing changed

Is this the only error you are getting? If yes, the execution should finish successfully, even if this warning is being printed out. 

If your execution fails, the problem might lie elsewhere.

Could you provide the execution log that is created in your directory where the notebook is?

**Comment by sam99dave** [comment]
Yeah, it worked. The warning appears but the execution completes. 
!2 successful and 13 failed due to 'too many requests'.

It turned out that the online notebook which I was using killed the execution forcefully.

Any suggestions for solving the 'too many request error'?

Thank you so much for your response @mlubej & @batic 🙌

**Comment by mlubej** [comment]
Glad it works.

> Any suggestions for solving the 'too many request error'?

Regarding this problem, it may help if you decrease number of threads/processes that you are using.  

You can either set the `max_threads` to a small-ish value (3) here

```python
add_data = SentinelHubInputTask(
    bands_feature=(FeatureType.DATA, 'BANDS'),
    bands = band_names,
    resolution=10,
    maxcc=0.8,
    time_difference=datetime.timedelta(minutes=120),
    data_source=DataSource.SENTINEL2_L1C,
    additional_data=[(FeatureType.MASK, 'dataMask', 'IS_DATA'),
                     (FeatureType.MASK, 'CLM'),
                     (FeatureType.DATA, 'CLP')]),
    max_threads = 3
```

and/or decrease the number of parallel workers here

```python
executor.run(workers=5, multiprocess=True)
```

**Comment by mlubej** [comment]
Closing.
