### ISSUE TITLE
Custom shapefile construction 

### ISSUE THREAD

**Issue by AnupJoseph** [sentinel-hub/eo-learn#221]
Can you suggest a method for constructing a shapefile for another region?
For replicating the LULC pipeline

**Comment by batic** [comment]
Typically one can get vector shapes for other regions either from official/governmental sources, or "draw" them using GIS software (e.g. QGIS).

You can have a look at low-res naturalearth dataset that comes with geopandas:

```python
import geopandas as gpd

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world.plot()
```

Good luck!
