### ISSUE TITLE
Exporting multiple masks with ExportToTiff

### ISSUE THREAD

**Issue by HamedAlemo** [sentinel-hub/eo-learn#224]
I'm trying to use `ExportToTiff` and export two different mask arrays (CLD and SCL) from an EOPatch, but `ExportToTiff` by default choses the first mask. I couldn't figure out anyway to define which mask to export, and the `band_indices` argument only applies to the data array not masks. 

* How to reproduce the issue:
```
input_task = SentinelHubInputTask(
    data_source = DataSource.SENTINEL2_L2A,
    bands= ['B02','B03','B04','B05','B06','B07','B08','B8A','B09','B11','B12'],
    bands_feature = (FeatureType.DATA, 'L2A_data'),
    additional_data = [(FeatureType.MASK, 'CLD'), (FeatureType.MASK, 'SCL')],
    resolution = resolution,
    config = config,
    max_threads = 1
)

workflow = LinearWorkflow(input_task)

result = workflow.execute({input_task: {'bbox': bbox, 'time_interval': time_interval}})
eopatch = result[0].eopatch()

task = ExportToTiff(feature=FeatureType.MASK, folder='')
task.execute(eopatch, filename="example_mask.tif")
```

* Expected outcome:
A tif file with two bands: one for CLD and one for SCL. Or possibility of choosing one of the masks to export. 

* Actual outcome: 
A tif file that only has the CLD mask. 

* OS package and version:
Debian GNU/Linux 10 (buster)
eo-learn 0.7.5

**Comment by mlubej** [comment]
Hi @HamedAlemo 

the `FeatureType.MASK` intentionally has only 1 feature, but that doesn't mean that a `MASK` feature can't also be a `DATA` feature. So you could make a new `DATA` feature which contains both the `CLD` and the `SCL` and export both indices. 

```python

f1 = eop.mask['CLD']
f2 = eop.mask['SCL']

eop.data['MERGED_FTR'] = np.concatenate([f1,f2], axis=-1)

task = ExportToTiff(feature=(FeatureType.DATA, 'MERGED_FTR'), folder='')
task.execute(eop, filename="example_mask.tif")
```

You also need to think about the temporal aspect of the data. If a `DATA` feature has features `F1` and `F2` at different times `F1(0), F1(1), ...` and `F2(0), F2(1), ...`, then your tiff file will have the following structure in case you export all features and all time indices: F1(0), F2(0), F1(1), F2(1), ..., F1(M), F2(M).

It is possible to split this further using `gdal`

**Comment by HamedAlemo** [comment]
Hi @mlubej 
Thanks for the explanation. So using your code I can do the same with mask arrays, and create separate tiff files for CLD and SCL masks:

```Python
task_SCL = ExportToTiff(feature=(FeatureType.MASK, 'SCL'), folder='')
task_CLD = ExportToTiff(feature=(FeatureType.MASK, 'CLD'), folder='')
```

I tried and this works for me. 

On the time component, I'm actually looping over time and creating separate files for each time. 


Thanks.

**Comment by mlubej** [comment]
Yes, using a separate export task for each feature also works. You can either use a separate task for each feature and band, or just push everything into a single tiff and then split the tiff afterwards, this way it might be less files.

Both work, so up to you!

Cheers!

Closing.
