### ISSUE TITLE
Add possibility to query orbitDirection in sentinelhub_service.py 

### ISSUE THREAD

**Issue by wouellette** [sentinel-hub/eo-learn#23]
For Sentinel-1, it is important to be able to use descending or ascending passes separately from one another, so a parameter for `orbitDirection` should be included in `sentinelhub_service.py` to do this, at least for the `S1IWWCSInput()` and `S1IWWMSInput()` methods.

The WMS configurator caters for this so I am sure it is a very quick fix that requires implementation.

**Comment by AleksMat** [comment]
Hi @wouellette.

Thanks for raising this issue. Orbit direction would be really useful parameter to have. We plan to implement this very soon.

**Comment by AleksMat** [comment]
Update about this feature:

Unfortunately current capabilities of Sentinel Hub services (specifically WFS) together with download process in `sentinelhub-py` don't allow easy filtering by orbit direction.  It is still on our todo list and is also quite important to feature to us. However it might take a while longer for this to be supported.

**Comment by devisperessutti** [comment]
This is now supported. The `S1` [input tasks](https://eo-learn.readthedocs.io/en/latest/eolearn.io.sentinelhub_service.html#eolearn.io.sentinelhub_service.S1IWWMSInput) accept an `orbit` argument which can either be (`'both'`, `'ascending'`, `'descending'`)
