### ISSUE TITLE
TestPatch in Features subpackage has inverted `IS_VALID` mask

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/eo-learn#233]
The TestPatch in the Features subpackage has an inverted `IS_VALID` mask which is used in the tests. The patch could be discarded anyway in favour of using the `examples_data/TestEOPatch`.

Image below shows the `ndvi` data of the test patch which is not `nan` and below the `IS_VALID` mask which is `False`.

![image](https://user-images.githubusercontent.com/37869250/88051089-5ad9b880-cb58-11ea-9775-567a56f65968.png)

Reported by @bsircelj, Thanks!

**Comment by AleksMat** [comment]
In `eo-learn` `1.0.0` that test EOPatch was discarded in favor of `examples_data/TestEOPatch`.
