### ISSUE TITLE
Can we use the Train_model.pkl file and predict the label for different AOI different latest date say 2020 july? 

### ISSUE THREAD

**Issue by visalikk** [sentinel-hub/eo-learn#237]
Can we use the Train_model.pkl file and predict the label for different AOI different latest date say 2020 july? Please assist to understand and share any sample

**Comment by AleksMat** [comment]
Hi @visalikk,

You certainly can take a model, trained with data from one year, and use it to make a prediction with data from a different year. Depending on how well your model generalizes such predictions will either achieve similar or worse accuracy than a prediction with data from the same year would achieve.

Feel free to try it out.

**Comment by visalikk** [comment]
can we get model.pkl for su_lulc . As training the model takes lot of computation power i am unable to do.
