### ISSUE TITLE
model.pkl for SI_LULC_

### ISSUE THREAD

**Issue by visalikk** [sentinel-hub/eo-learn#242]
Hi, 

Due to memory constraints i am unable to train and produce model.pkl file from SI_LULC...ipynb code for land cover. Can you provide the model.pkl file for 2019 trained dataset. It would be great to run predictictions on that .  Please let me know on this.

Thanks,
Visa

**Comment by mlubej** [comment]
I already responded and attached the model [here](https://github.com/sentinel-hub/eo-learn/issues/231#issuecomment-669386209). Closing
