### ISSUE TITLE
Above ground biomass calculation using Sentinel 1 & 2 data

### ISSUE THREAD

**Issue by visalikk** [sentinel-hub/eo-learn#243]
Hi Team,

I am using sentinel data to predict AGB for mangroves. Do u have any sample code where i can use  Sentinel & Lidar elevation details together and calculate biomass using Machine learning models. Kindly assist.

Thanks,

**Comment by mlubej** [comment]
Hi @visalikk 
unfortunately, we don't have any code prepared in advance for the specific project that you mention. There are a few tutorials in the [sh-py](https://github.com/sentinel-hub/sentinelhub-py/blob/master/examples/processing_api_request.ipynb) and [other eolearn](https://github.com/sentinel-hub/eo-learn/blob/master/examples/io/SentinelHubIO.ipynb) examples which you can use and might assist you in the right direction. `eo-learn` is primarily a tool which you can use to make projects like this, but not really a repository for various projects (at least not yet). If you manage to put anything together, you are welcome to make a PR and contribute to the project.

Good luck!
