### ISSUE TITLE
SentinelHubInputTask for Landsat-8

### ISSUE THREAD

**Issue by JDESLOIRES** [sentinel-hub/eo-learn#246]
Hi,

I am trying to download Landsat-8 using SentinelHubInputTask intead of L8L1CWCSInput. 

Indeed, I have recently switched from S2L2AWCSInput to SentinelHubInputTask and I have seen that the shapes of the arrays inside the eopatch may not be the same from those two functions. 
Maybe the spatial interpolation methodology has changed since ?

However, I was concatenated Sentinel-2 images with Landsat-8 and I get now different shape if I still use L8L1CWCSInput (while I had the same shapes using S2L2AWCSInput).

In SentinelHubInputTask , I have tried data_source = LANDSAT8 or LANDSAT8_L1C or LANDSAT8_L2A and I had those errors :

- LANDSAT8_L2A : 
DownloadFailedException: During execution of task SentinelHubInputTask: Failed to download from:
https://services.sentinel-hub.com/ogc/wfs/c58dad51-7b2c-4778-9bc5-35d1924ae581?SERVICE=wfs&WARNINGS=False&REQUEST=GetFeature&TYPENAMES=SEN4CAP_L8L2A.TILE&BBOX=46.1250412351719%2C-0.927684903144836%2C46.127483911982%2C-0.923398733139038&OUTPUTFORMAT=application%2Fjson&SRSNAME=EPSG%3A4326&TIME=2018-04-01T00%3A00%3A00%2F2018-07-01T23%3A59%3A59&MAXCC=80.0&MAXFEATURES=100&FEATURE_OFFSET=0
with HTTPError:
400 Client Error: Bad Request for url: https://services.sentinel-hub.com/ogc/wfs/c58dad51-7b2c-4778-9bc5-35d1924ae581?SERVICE=wfs&WARNINGS=False&REQUEST=GetFeature&TYPENAMES=SEN4CAP_L8L2A.TILE&BBOX=46.1250412351719%2C-0.927684903144836%2C46.127483911982%2C-0.923398733139038&OUTPUTFORMAT=application%2Fjson&SRSNAME=EPSG%3A4326&TIME=2018-04-01T00%3A00%3A00%2F2018-07-01T23%3A59%3A59&MAXCC=80.0&MAXFEATURES=100&FEATURE_OFFSET=0
Server response: "TYPENAME=SEN4CAP_L8L2A.TILE is invalid!"

- LANDSAT8_L1C :
KeyError: "During execution of task SentinelHubInputTask: <DataSource.LANDSAT8_L1C: (<_Source.LANDSAT8: 'Landsat 8'>, <_ProcessingLevel.L1C: 'L1C'>)>"

- LANDSAT8 : 
KeyError: "During execution of task SentinelHubInputTask: <DataSource.LANDSAT8: (<_Source.LANDSAT8: 'Landsat 8'>, <_ProcessingLevel.L1TP: 'L1TP'>)>"

 Would you know how could I do? Is SentinelHubInputTask is only available now for Sentinel-2 ?

Thanks a lot and feel free to ask me for any further information.

Best regards,
Johann

**Comment by batic** [comment]
Hi @JDESLOIRES,

Thanks for reporting this. At the moment, `SentinelHubInputTask` doesn't work with Landsat8 data, so you will have to use `L8L1CWCSInput` task. Sorry for the inconvenience, we'll probably address this in future updates.

Regarding the differences in shapes between `SentineHubInputTask` and `S2L2AWCSInput`: you should get the same results provided the requests to the SH service both ask for the same image width/height. See all examples/io/RequestDataComparison.ipynb.

Regards,
Matej

**Comment by JDESLOIRES** [comment]
Hi Matej,

Thank you for your message. Sure, it would be awesome to be able to download other data sources than Sentinel-2 through SentinelHubInputTask. 

I did the check yesterday and I did not have exactly the same shape for my area of interest (we can have +1/-1 in the height/width but it is not always the case, mostly on small images). 
One example would be the following bounding box (-0.927684903144836,46.1250412351719,-0.923398733139038,46.127483911982). 

Regards,
Johann

**Comment by batic** [comment]
Hi Johann,

I am able to reproduce the +1/-1 differences in responses between `SentineHubInputTask` and `*WCSInput`. The differences come from the fact that with `SentinelHubInputTask` the window width and hight is computed in Python, if one specifies resolution, while for `WCSInput`, resolution (in m) is passed to the SH service.

Thank you for reporting this.

Best,
Matej

**Comment by AleksMat** [comment]
This has been fixed in the latest `eo-learn` release `0.8.0`.
