### ISSUE TITLE
 Land-Use-Land-Cover Prediction for Slovenia example

### ISSUE THREAD

**Issue by anhfit** [sentinel-hub/eo-learn#251]
I have tried this example, but got an error when running the below block . Because the save eopatch_1;..eopatch_24 can not be saved to the disk. I am using eo-learn docker (the latest version). I also uploaded the generated log file.

Many thanks,
-------------------------------------
[eoexecution-1.log](https://github.com/sentinel-hub/eo-learn/files/5210459/eoexecution-1.log)
 
%%time

# Execute the workflow
time_interval = ['2019-01-01', '2019-12-31'] # time interval for the SH request

# define additional parameters of the workflow
execution_args = []
for idx, bbox in enumerate(bbox_list[patchIDs]):
    execution_args.append({
        add_data:{'bbox': bbox, 'time_interval': time_interval},
        save: {'eopatch_folder': f'eopatch_{idx}'}
    })
    
executor = EOExecutor(workflow, execution_args, save_logs=True)
executor.run(workers=5, multiprocess=True)

executor.make_report()

**Comment by mlubej** [comment]
Hi @anhfit!

It seems that your credentials for SH might not be set up properly.

```
{"error":{"status":400,"reason":"Bad Request","message":"Illegal client_id","code":"OAUTH_ERROR"}}.
```

Please check the configuration instructions [here](https://sentinelhub-py.readthedocs.io/en/latest/configure.html). 

Let me know if you still have problems after this :) 

Cheers,
Matic

**Comment by anhfit** [comment]
Many thanks @mlubej , solved !
