### ISSUE TITLE
Kernel died when fitting model tree-cover-keras

### ISSUE THREAD

**Issue by anhfit** [sentinel-hub/eo-learn#252]
I am trying the example tree-cover-keras, when executing model.fit() then it informs that Kernel died.
Any suggestion to overcome this issue. Many thanks.

**Comment by mlubej** [comment]
Hi @anhfit,

Do you get any other error messages or stack trace? Any more information would help. Additionally, this is one of the notebooks which is not maintained anymore, so we apologize if, in the end, we will not be able to help you.

Regards,
Matic

**Comment by anhfit** [comment]
![image](https://user-images.githubusercontent.com/7801361/93326199-a2bc4980-f842-11ea-9016-02c78bfce64c.png)
# Fit the model
batch_size = 16
model.fit(
        train_gen.flow(x_train, y_train, batch_size=batch_size),
        steps_per_epoch=len(x_train),
        epochs=20,
        verbose=1)
model.save(op.join('model.h5'))

Jupyter informs this error when reaching the below code lock

**Comment by mlubej** [comment]
My guess is that you run out of resources. Try decreasing the `batch_size` and/or number of epochs. @devisperessutti what do you think?

**Comment by anhfit** [comment]
Many thanks @mlubej . Tried to decrease both batch_size and numbers of epochs, then it worked.
