### ISSUE TITLE
[HELP] Upgrade guide to 0.8.0

### ISSUE THREAD

**Issue by mjavorka** [sentinel-hub/eo-learn#260]
You recently released version [0.8.0](https://github.com/sentinel-hub/eo-learn/releases/tag/v0.8.0) of `eo-learn` package. I saw there many breaking changes not compatible with older versions. 

Do you have an **upgrade guide** for implementing changes from the new release?

**Comment by AleksMat** [comment]
Hi @mjavorka,

Here are the latest release notes:

- [eo-learn releases](https://github.com/sentinel-hub/eo-learn/releases)
- [sentinelhub-py releases](https://github.com/sentinel-hub/sentinelhub-py)

Version `0.8.0` is not introducing too many code-breaking changes. The main one is changing terminology of "data source" into "data collection". That has been done in `sentinelhub-py` and `eo-learn`. Therefore you'll have to change any `DataSource` class to `DataCollection` and any `data_source` parameter to `data_collection`. We also made sure that the old naming still works, it just raises deprecation warnings.

When you upgrade to `eo-learn` `0.8.0` also please make sure to upgrade all `eo-learn` subpackages to `0.8.0` as well and `sentinelhub-py` to version `3.1.0`. If you are using pip that will happen automatically. However, if you are using conda you'll have to do it manually and even use pip withing the conda environment to upgrade eo-learn subpackages.

In case you'll be still getting any weird errors please let us know.

**Comment by AleksMat** [comment]
Feel free to reopen in case of any more questions.
