### ISSUE TITLE
SentinelHubInputTask attribute error: 'DataCollection' object has no attribute 'is_custom'

### ISSUE THREAD

**Issue by JmeCS** [sentinel-hub/eo-learn#261]
When instantiating a `SentinelHubInoutTask` object following the example in "Land Use Land Cover" example in the documentation, I get the following error:

```
Traceback (most recent call last):
  File "/Users/jameysmith/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-57ff3821ad92>", line 11, in <module>
    max_threads=5
  File "/Users/jameysmith/opt/miniconda3/envs/sent-request/lib/python3.7/site-packages/eolearn/io/processing_api.py", line 248, in __init__
    elif data_source.is_custom() and not bands:
  File "/Users/jameysmith/opt/miniconda3/envs/sent-request/lib/python3.7/site-packages/sentinelhub/data_collections.py", line 495, in __getattr__
    return super().__getattribute__(item, *args, **kwargs)
AttributeError: 'DataCollection' object has no attribute 'is_custom'
```

Here is the code (should be fully reproducible):

```
from eolearn.io import SentinelHubInputTask
from eolearn.core import FeatureType
import datetime
from sentinelhub import DataSource

add_data = SentinelHubInputTask(
    bands_feature=(FeatureType.DATA, 'BANDS'),
    bands=['B04', 'B08']
    resolution=10,
    maxcc=0.8,
    time_difference=datetime.timedelta(minutes=120),
    data_source=DataSource.SENTINEL2_L1C,
    additional_data=[(FeatureType.MASK, 'dataMask', 'IS_DATA'),
                     (FeatureType.MASK, 'CLM'),
                     (FeatureType.DATA, 'CLP')],
    max_threads=5
)
```

It seems to be an issue with the `DataCollection` vs. the newer `DataSource`. The trace in the error message references the DataCollection class from `data_collections.py` regardless of whether I try to provide a `DataSource` or `DataCollections` object to `SentinelHubInputTask`

**Python version:**
3.7.3

**EOLearn versions:**
eo-learn-core - 0.8.0
eo-learn-io - 0.7.7

**Sentinelhub version**:
3.1.0

**Comment by mlubej** [comment]
Hi @JmeCS,

there was a bug discovered yesterday, perhaps it's related to your issue. Check https://github.com/sentinel-hub/eo-learn/issues/263

No fix yet, but perhaps you can manually fix [this line](https://github.com/sentinel-hub/eo-learn/blob/09285d22fc6cf33af359fbaf85c5426e9a2d09f2/io/eolearn/io/processing_api.py#L256) in the code and check if then things work.

**Comment by AleksMat** [comment]
Hi @JmeCS,

Please upgrade `eo-learn-io` version to `0.8.0`. It is available via pip. After that please rename parameter `data_source` to `data_collection`.
