### ISSUE TITLE
Converting eo-learn framework to R with reticulate package

### ISSUE THREAD

**Issue by BatuhanKavlak** [sentinel-hub/eo-learn#265]
Hey guys, do you consider converting the framework to the R users. For example, there is ```rgee``` alternative to ```geemap``` built on ```reticulate``` package:

[geemap](https://github.com/giswqs/geemap) - Python package for using Earth Engine on Python more conveniently.
[rgee](https://github.com/r-spatial/rgee) - R alternative to ```geemap```.

I'll look at how this framework can be converted to R. I wonder if you have already thought this and had a plan.

**Comment by gmilcinski** [comment]
HI @BatuhanKavlak,
we have no mid-term plans to convert eo-learn to R as we are using Python intensively internally. We do also not have sufficient R expertise. 
That being said, eo-learn is open-source and contributions by the community are always welcome.

Best,
Grega
