### ISSUE TITLE
brokenprocesspool

### ISSUE THREAD

**Issue by sanjivjha** [sentinel-hub/eo-learn#268]
After running some time it workflow executing stop with the message

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

What is the good way to debug what is the issue? 
There is nothing in log files

**Comment by mlubej** [comment]
Hi @ sanjivjha!

Sometimes this happens in eo-learn when multiple instances are using multiprocessing. If you are downloading and/or using s2cloudless, it is better to set the `max_threads` parameter in the `SentinelHubInputTask` and to set `multiprocess=False` in the `EOExecutor`. It seems there is a clash in such cases, while for other tasks multiprocessing should work.

Perhaps I could help more if you wrote a bit more detail about your workflow.

**Comment by sanjivjha** [comment]
Thanks, This helped!
