### ISSUE TITLE
AddMultiCloudMaskTask fails to load 'pixel_s2_cloud_detector_lightGBM_v0.2.joblib.dat' and  S2PixelCloudDetector does not work when passed as mono_classifier

### ISSUE THREAD

**Issue by xen0f0n** [sentinel-hub/eo-learn#278]
I'm trying to use AddMultiCloudMaskTask but when using the default mono_classifier argument, joblib fails to load the model
```
if self._mono_classifier is None:
    self._mono_classifier = joblib.load(os.path.join(self.MODELS_FOLDER, MONO_CLASSIFIER_NAME))
```
and throws error 
```
{ModuleNotFoundError}'No module named sklearn.preprocessing.label'
```

Next thing I tried was to pass ```S2PixelCloudDetector``` as ```mono_classifier``` argument. 
But I got 
```
{AttributeError}'S2PixelCloudDetector' object has no attribute 'predict_proba'
```
, which is fine, because S2PixelCloudDetector has a function called ```get_cloud_probability_maps```. 

When I tried running on the debugger, it complained about the input shape, and that it requires 4-d arrays. 
Also, during debugging, I've found that this line works:
```execute_with_mp_lock(self.mono_classifier.get_cloud_probability_maps, bands_t)```.

My code is the following:

```
band_names = ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']
add_data = SentinelHubInputTask(
    bands_feature=(FeatureType.DATA, 'BANDS'),
    bands=band_names,
    resolution=10,
    maxcc=0.5,
    time_difference=datetime.timedelta(days=10),
    data_collection=DataCollection.SENTINEL2_L1C,
    additional_data=[(FeatureType.MASK, 'dataMask', 'IS_DATA')]
)

add_clm = AddMultiCloudMaskTask(mono_classifier=S2PixelCloudDetector(),
                                data_feature='BANDS',
                                all_bands=True,
                                max_proc_frames=1,
                                processing_resolution=160,
                                mono_features=('CLP', 'CLM'),
                                mask_feature=None,
                                average_over=16,
                                dilation_size=8)
```
I'm using eo-learn==0.8.0 and scikit-learn==0.24.1.

Any ideas?

**Comment by AleksMat** [comment]
Hi @xen0f0n,

The latest `scikit-learn` `0.24` is not compatible with this particular task in `eo-learn`. In the next `eo-learn` release we intend to fix this but for now please use `scikit-learn<0.24`.

**Comment by xen0f0n** [comment]
@AleksMat  thanks!
