### ISSUE TITLE
Failed eopatch_1_col-0_row-1 with During execution of task SentinelHubInputTask:

### ISSUE THREAD

**Issue by Ehsan125** [sentinel-hub/eo-learn#285]
I am trying to run the `examples` present at the location `eo-learn/examples/crop-type-classification/` in your github repository, while executing the following cell:

> # execute workflow and save the names of those that failed
> failed = []
> 
> for patch_name in tqdm(patch_list):
>     # add EO data if possible
>     try:
>         workflow.execute({load: {'eopatch_folder': patch_name},
>                           add_l2a: {'time_interval': time_interval},
>                           #add_sc_feature: {'data': {}},
>                           #add_rl_feature: {'data': {}},
>                           save: {'eopatch_folder': patch_name}})
>     # append EOPatch name to list for further investigation
>     except Exception as ex:
>         print(f'Failed {patch_name} with {ex}')
>         failed.append(patch_name)
> 

I am getting the following error: 

```
Failed eopatch_1_col-0_row-1 with During execution of task SentinelHubInputTask: Configuration parameters 'sh_client_id' and 'sh_client_secret' have to be set in order to authenticate with Sentinel Hub service
Failed eopatch_2_col-1_row-0 with During execution of task SentinelHubInputTask: Configuration parameters 'sh_client_id' and 'sh_client_secret' have to be set in order to authenticate with Sentinel Hub service
Failed eopatch_0_col-0_row-0 with During execution of task SentinelHubInputTask: Configuration parameters 'sh_client_id' and 'sh_client_secret' have to be set in order to authenticate with Sentinel Hub service
Failed eopatch_3_col-1_row-1 with During execution of task SentinelHubInputTask: Configuration parameters 'sh_client_id' and 'sh_client_secret' have to be set in order to authenticate with Sentinel Hub service
```
I have set the client name and secrets in above cells, but still getting this error i am unable to understand, please guide me how to remove this error, i am also attaching the screenshot for much clarity. Thank you 

![Screenshot from 2021-03-31 14-22-43](https://user-images.githubusercontent.com/45161966/113122016-a9ce0680-922c-11eb-85ec-7422e121ad56.png)

**Comment by AleksMat** [comment]
Hi @Ehsan125,

Please make sure that the `config` object, that is passed to `SentinelHubInputTask` as a parameter, contains valid `sh_client_id` and `sh_client_secret` attributes.

**Comment by Ehsan125** [comment]
I am attaching the screenshot, the configuration cell was ran successfully, and i do not know how can i check the validity of this in config object, please enlighten me. 
![Screenshot from 2021-03-31 14-48-54](https://user-images.githubusercontent.com/45161966/113125850-75f4e000-9230-11eb-9374-d7e9f1016a0a.png)

**Comment by AleksMat** [comment]
There are 2 problems:

- Your code does not set credentials, it just compares existing, probably empty, credentials with your credentials. The code should be something like:

```Python
config = SHConfig()
config.sh_client_id = '<your client id>'
config.sh_client_secret = '<your client secret>'

if config.sh_client_id == '' or config.sh_client_secret == '':
    print("Warning! To use Sentinel Hub services, please provide the credentials (client ID and client secret).")
```

- You are trying to set your username instead of an OAuth client id. Please check [this part of the tutorial video](https://www.youtube.com/watch?v=CBIlTOl2po4&t=1760s) that shows what exactly OAuth client id is. Your OAuth client secret is seems to be ok.

The notebook also contains a link to [configuration instructions](https://sentinelhub-py.readthedocs.io/en/latest/configure.html#configuration) with all this information and more.

**Comment by Ehsan125** [comment]
Thank you for your valuable addition in code, i have followed the exacts steps of getting the OAuth client id and secrets, as your suggested video tutorial, now i am getting the following error:
![Screenshot from 2021-03-31 15-32-20](https://user-images.githubusercontent.com/45161966/113131224-6082b480-9236-11eb-9715-bec10fd4a478.png)


> Failed eopatch_1_col-0_row-1 with (During execution of task SentinelHubInputTask: ({'status': 400, 'reason': 'Bad Request', 'message': 'Illegal client_id', 'code': 'OAUTH_ERROR'}) ) 
> Failed eopatch_2_col-1_row-0 with (During execution of task SentinelHubInputTask: ({'status': 400, 'reason': 'Bad Request', 'message': 'Illegal client_id', 'code': 'OAUTH_ERROR'}) ) 
> Failed eopatch_0_col-0_row-0 with (During execution of task SentinelHubInputTask: ({'status': 400, 'reason': 'Bad Request', 'message': 'Illegal client_id', 'code': 'OAUTH_ERROR'}) ) 
> Failed eopatch_3_col-1_row-1 with (During execution of task SentinelHubInputTask: ({'status': 400, 'reason': 'Bad Request', 'message': 'Illegal client_id', 'code': 'OAUTH_ERROR'}) )

**Comment by AleksMat** [comment]
I suspect that your OAuth client id is still not correct.

**Comment by Ehsan125** [comment]
Thank you soo much for your help, you are pro. I have solved the error by your help, now it is taking too long to fill the process bar. i do not know why? i am closing at least this issue.
