### ISSUE TITLE
How to use eo-learn tasks to load local saved Sentinel-2 data? 

### ISSUE THREAD

**Issue by musbandishoev** [sentinel-hub/eo-learn#292]
**What is the problem? Please describe.**

A clear and concise description of what the problem is.

**Here's the solution**

**Alternatives**

**Additional context**

**Comment by batic** [comment]
Please provide more information - the template to provide relevant info is given so that it helps us understand your issue... 

If you don't provide additional details, we cannot help you.

**Comment by musbandishoev** [comment]
How I can I load Sentinel-2 images (SAFE) -downloaded to disk - using eo-learn and than safe  it to EOpatch format.

**Comment by musbandishoev** [comment]
thanks for your prompt reply...
