### ISSUE TITLE
[BUG] I was reading the article titles "Land Cover Classification with eo-learn: Part 1" an came across this notebook example. But there is always an error and I'm not able to see the example. It signals the message "Something went wrong"."

### ISSUE THREAD

**Issue by imhaseebkhan** [sentinel-hub/eo-learn#299]
**Describe the bug**

NOTE: Remove any confidential information, such as Sentinel Hub credentials!

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Environment**

Details of the python environment

**Stack trace or screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by AleksMat** [comment]
Hi @imhaseebkhan,

I suggest pulling the chages from the current master or develop branch and stashing any local changes you might have done. Besides from that you will have to be more specific what exactly you are trying to do.

Closing the issue until any more information is provided.
