### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by LambertMark** [sentinel-hub/eo-learn#30]
I'm trying to install eo-learn on a windows machine.  After I use `pip install eo-learn`, I get the following error:

![image](https://user-images.githubusercontent.com/20894713/48091696-05b51200-e1d0-11e8-8a16-67c4f8ccfbf2.png)

The error claims that more information is available in the README, but the README does not mention anything about windows installation.  I did add the path to my GDAL_VERSION as a system variable.  I am using a python 3.5 environment with Anaconda.

**Comment by batic** [comment]
The problem seems to be with the installation of rasterio on windows. Have you tried looking for solutions there?

**Comment by LambertMark** [comment]
You're right, rasterio does have windows-specific instructions.  Closing.
