### ISSUE TITLE
[BUG] Corrupted geojson file in example data

### ISSUE THREAD

**Issue by ilkinumarov9** [sentinel-hub/eo-learn#302]
I am trying to reproduce [LULC Prediction for Slovenia](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html) example notebook from documentation; When I try to read the file provided in [example_data/svn_border.geojson](https://github.com/sentinel-hub/eo-learn/blob/master/example_data), using

```
import geopandas as gpd

country = gpd.read_file(r"‪path-to-file\svn_border.geojson")
```
It gives the following error:
> DriverError: '‪path-to-file\svn_border.geojson' not recognized as a supported file format.

I have tried to read another geojson file with the same function and it worked. When I tried to validate svn_border.geojson on 

[geojsonlint.com](geojsonlint.com) this message came up:

> Invalid GeoJSON
> Line 0: Parse error on line 1:

I am using Python 3.6.8, Fiona 1.18 and GDAL 3.1.4

I think geojson file given in the repo might be corrupted. Any ideas?

**Comment by batic** [comment]
Sorry, cannot reproduce your error.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/2518145/118768642-8b28db00-b87f-11eb-87f5-88b80098f8e5.png">

Could you check your geopandas version?

PS: It also gets displayed properly in QGIS:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/2518145/118769208-33d73a80-b880-11eb-8e80-6f732a0016e6.png">

**Comment by mlubej** [comment]
Hi @ilkinumarov9 

The cause of your issues in in the error output:

    DriverError: '‪path-to-file\svn_border.geojson' not recognized as a supported file format.

Not sure where you got `‪path-to-file`, since it's not in the notebook, but you have to put the actual location to the file.

Hope this fixes the issue!

**Comment by ilkinumarov9** [comment]
@mlubej I have replaced actual path with path-to-file for posting purpose. I have double-checked the path, it was correct.
as @batic pointed out, I have checked my geopandas version, which was 0.9.0 . After downgrading it to the 0.8.1, I again encountered with the same error.
@batic's screenshot displays that file is OK, which means I have another error not related to data. I will look into that.

**Comment by batic** [comment]
I've tried with latest geopandas (0.9.0) and it also loads the file without errors, so yes, something else must be going on.

**Comment by AleksMat** [comment]
Hi @ilkinumarov9,

Here are some more suggestions what could be wrong:

- This path `r"‪path-to-file\svn_border.geojson"` seems suspicious:
  - please make sure to use the correct path to the geojson file on your filesystem,
  - the path can either be an absolute path or a relative path from your notebook to the file,
  - try using normal strings instead of raw strings,
    * character `\` is with normal strings written as `'\\'`,
  - in case you are using Windows continue using `\` in file path but if you are using Linux use `/` characters instead.

- In case your OS has a different default encoding it could help if you add parameter `encoding='utf-8'` to `gpd.read_file` function. But it is very unlikely.

If any of this doesn't work, please provide:

- the full path that you are trying to use.
- the full stack trace of the error, not just the error message.

**Comment by ilkinumarov9** [comment]
Hi @AleksMat 

First, I have downloaded another geojson file(`azegrid.json`) and put both geojson files into the same directory with notebook. I have tried to read `azegrid.geojson` using both absolute and relative path:
```
df_a1 = gpd.read_file("aze_grid.geojson")
df_a2 = gpd.read_file(r"C:\Users\IlkinU\1Project\aze_grid.geojson")
df_a3=gpd.read_file("C:\\Users\\IlkinU\\1Project\\aze_grid.geojson")

df_a1.plot()
df_a2.plot()
df_a3.plot()

```
Result:
![sc](https://user-images.githubusercontent.com/41194210/118934530-8174a580-b95b-11eb-97ac-6392788e935e.PNG)





Then I have tried the same thing with `svn_border.geojson` file.

`df_s1 = gpd.read_file(r"C:\Users\IlkinU\1Project\svn_border.geojson")`

`df_s2 = gpd.read_file("svn_border.geojson")`

`df_s3=gpd.read_file("C:\\Users\\IlkinU\\1Project\\svn_border.geojson")`


All three returned the same error trace and I am posting one of them:
> CPLE_OpenFailedError                      Traceback (most recent call last)
> fiona\_shim.pyx in fiona._shim.gdal_open_vector()
> 
> fiona\_err.pyx in fiona._err.exc_wrap_pointer()
> 
> CPLE_OpenFailedError: 'svn_border.geojson' not recognized as a supported file format.
> 
> During handling of the above exception, another exception occurred:
> 
> DriverError                               Traceback (most recent call last)
> <ipython-input-33-e7c0c88126b6> in <module>
> ----> 1 df_s2 = gpd.read_file("svn_border.geojson")
> 
> c:\users\ilkinu\appdata\local\programs\python\python36\lib\site-packages\geopandas\io\file.py in _read_file(filename, bbox, mask, rows, **kwargs)
>      94 
>      95     with fiona_env():
> ---> 96         with reader(path_or_bytes, **kwargs) as features:
>      97 
>      98             # In a future Fiona release the crs attribute of features will
> 
> c:\users\ilkinu\appdata\local\programs\python\python36\lib\site-packages\fiona\env.py in wrapper(*args, **kwargs)
>     398     def wrapper(*args, **kwargs):
>     399         if local._env:
> --> 400             return f(*args, **kwargs)
>     401         else:
>     402             if isinstance(args[0], str):
> 
> c:\users\ilkinu\appdata\local\programs\python\python36\lib\site-packages\fiona\__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
>     258         if mode in ('a', 'r'):
>     259             c = Collection(path, mode, driver=driver, encoding=encoding,
> --> 260                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
>     261         elif mode == 'w':
>     262             if schema:
> 
> c:\users\ilkinu\appdata\local\programs\python\python36\lib\site-packages\fiona\collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
>     160             if self.mode == 'r':
>     161                 self.session = Session()
> --> 162                 self.session.start(self, **kwargs)
>     163             elif self.mode in ('a', 'w'):
>     164                 self.session = WritingSession()
> 
> fiona\ogrext.pyx in fiona.ogrext.Session.start()
> 
> fiona\_shim.pyx in fiona._shim.gdal_open_vector()
> 
> DriverError: 'svn_border.geojson' not recognized as a supported file format.


Please refer to this image to see the file structure:

![scr](https://user-images.githubusercontent.com/41194210/118934866-e6c89680-b95b-11eb-9f44-6b9f42f46292.PNG)


I am using Windows 10 OS. May be I miss something here which you can point out? Or might at be related to OS/file settings and permissions? I am using company PC right now.

**Comment by AleksMat** [comment]
Ok, at least we now know that it is not an issue with file paths or with the Python environment as you were able to read the other file without any problems. Some other ideas:

- Is it possible that you somehow modified the content of this file? Could you perhaps redownload it from GitHub?
- Have you checked the content of the file? You can open it in a text editor as it is basically a JSON file with geographical information.
- File permissions are definitely worth checking and increasing. This is something that is specific to your OS configuration.

**Comment by ilkinumarov9** [comment]
Finally, solved. I somehow modified the file, which broke the json structure. I actually downloaded it again before, not sure how I modified the file twice without knowing but downloading the file third time solved the problem.
Thank you for your help and sorry for all the trouble!
