### ISSUE TITLE
[HELP] AddGeopediaFeature

### ISSUE THREAD

**Issue by LOActualControl** [sentinel-hub/eo-learn#306]
Hi all,

I am quite new to the EO space, so apologies if this is a dumb or simple question! I also realize I'm working off an example notebook that is no longer updated, so I understand if this issue cannot be solved. 

Anyway, when I run up to Cell 9 in [this notebook](https://github.com/sentinel-hub/eo-learn/blob/master/examples/tree-cover-keras/tree-cover-keras.ipynb), I get the error:

"ValueError: During execution of task AddGeopediaFeature: operands could not be broadcast together with shapes (640,779,3) (4,)"

I've looked through the forums and existing issues/questions but haven't found one that addresses the differing operands. It seems like the issue is with Geopedia rather than the Sentinel 2 data but I'm not 100% sure about that.

The other thing that could be at the root is that the ground truth data I'm using is the EU Tree Cover Geopedia data, while my AOI (the paradise.geojson file) is over northern California. Some screenshots are attached - any help resolving this would be greatly appreciated and once again, apologies if it's a silly question :)

<img width="819" alt="Screen Shot 2021-06-07 at 3 03 18 PM" src="https://user-images.githubusercontent.com/85516709/121074199-88941400-c7a1-11eb-9978-fb7504a80a1a.png">
<img width="862" alt="Screen Shot 2021-06-07 at 3 03 12 PM" src="https://user-images.githubusercontent.com/85516709/121074201-892caa80-c7a1-11eb-8ce4-f50720fb8f9d.png">
<img width="646" alt="Screen Shot 2021-06-07 at 3 03 03 PM" src="https://user-images.githubusercontent.com/85516709/121074203-892caa80-c7a1-11eb-8296-8f495e7ef235.png">

**Comment by LOActualControl** [comment]
FYI link to forum post here: https://forum.sentinel-hub.com/t/addgeopediafeature-issue-in-eo-learn-tree-cover-example/3927

**Comment by batic** [comment]
Hi @LOActualControl,

As stated at the beginning of the notebook, it might not work; unfortunately for you, this seems to be true.

Digging deeper, the issue is that Geopedia returns a 3-band data and not 4, so the mapping of colors to values (using  `raster_value` dict) fails.

The way to remedy this is to drop the 4th value from RGBA arrays (i.e. alpha) in the dict, which is - for some reason - not returned from Geopedia, like so:
```python
raster_value = {
    '0%': (0, [0, 0, 0]),
    '10%': (1, [163, 235,  153]),
    '30%': (2, [119, 195,  118]),
    '50%': (3, [85, 160, 89]),
    '70%': (4, [58, 130, 64]),
    '90%': (5, [36, 103, 44])
}
```

Hope the rest of the notebook will not give you too much trouble. If you need to change something to make it work, please contribute back to the community - create a PR.

Best,
Matej

**Comment by LOActualControl** [comment]
Thanks Matej! I just tried it again with the corrected dictionary and it worked like a charm. I'm going through the rest of the notebook now and will reach out if I run into any other issues. And if I don't, I'll add a PR with the things I tweaked to make it work. Thanks again!

**Comment by LOActualControl** [comment]
Ok so now while the code itself runs, I don't think it's detecting any actual tree cover data in my AOI. When I run the unet model, it runs with 100% accuracy, which tells me something bad is probably going on. I played with a few example patches that should include tree cover in my AOI and none of them have any detected tree cover. Further, when I run cell 13 in the notebook, it gives me the following error:

"Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers)"

I've noticed there are also some discrepancies between my example eo-patch data and the notebook's example eo-patch data (in [cell 12](https://github.com/sentinel-hub/eo-learn/blob/master/examples/tree-cover-keras/tree-cover-keras.ipynb)), which I've highlighted below, that may be at the root of the issue. I'd be hugely grateful for any help resolving the issues but also completely understand if they can't be solved given the outdated notebook. Thanks!

<img width="986" alt="Screen Shot 2021-06-09 at 3 31 53 PM" src="https://user-images.githubusercontent.com/85516709/121417608-19045d00-c938-11eb-8311-69eaed29b1a0.png">
<img width="996" alt="Screen Shot 2021-06-09 at 3 31 39 PM" src="https://user-images.githubusercontent.com/85516709/121417619-1bff4d80-c938-11eb-977e-7f3954a6e53e.png">

**Comment by LOActualControl** [comment]
Ok I think it ended up being a very, *very* newbie problem. I tried the notebook with a Europe AOI and the whole thing worked fine...I didn't realize the ground truth data you use has to cover the AOI that you're interested in...oops.

**Comment by batic** [comment]
Indeed, the training data in this example is EU Tree Cover data. You could train it on EU, and then try and apply it in your AOI, but don't expect too much as the tree cover in CA is probably rather different from the EU one.
