### ISSUE TITLE
[HELP]GEE to eo-learn

### ISSUE THREAD

**Issue by nagatho** [sentinel-hub/eo-learn#309]
**Question**

I am trying to send data from GEE to eo-learn.
But I am unable to do that.
Can any one help me to do this?  

**Additional context**

I already downloaded data in to the google drive.

**Comment by AleksMat** [comment]
Hi @nagatho,

So far eo-learn doesn't have any integrations with GEE. But you can always implement your own custom EOTasks for that.

Also feel free to describe any functionality you would need or make a contribution to eo-learn.

**Comment by nagatho** [comment]
Thank you.

Can you explain about 'eolearn.io.local_io.ImportFromTiff(*args, **kwargs)' this?

How I can import geotiff files to this and get the out put and at last save this data for further use. 

Eg:-
I have tiff file that include all 16 bands.
I want to convert this data like below
![image](https://user-images.githubusercontent.com/46887166/123767585-35ffd080-d8e5-11eb-8103-5a30ded795f8.png)

**Comment by AleksMat** [comment]
The following resources should help you out:

- [documentation of `ImportFromTiff` class](https://eo-learn.readthedocs.io/en/latest/eolearn.io.local_io.html#eolearn.io.local_io.ImportFromTiff),
- [example notebook](https://github.com/sentinel-hub/eo-learn/blob/master/examples/batch-processing/how_to_timelapse/how_to_timelapse.ipynb) which uses `ImportFromTiff` somewhere in the process.

**Comment by nagatho** [comment]
Thank you for your response.

**Comment by AleksMat** [comment]
Closing this for now.
