### ISSUE TITLE
Running in Binderhub

### ISSUE THREAD

**Issue by psychemedia** [sentinel-hub/eo-learn#31]
I just tried running one of the demo notebooks  — [`examples/water-monitor/WaterMonitorWorkflow.ipynb`](https://github.com/sentinel-hub/eo-learn/blob/master/examples/water-monitor/WaterMonitorWorkflow.ipynb) — using Binderhub ([direct link](https://mybinder.org/v2/gh/sentinel-hub/eo-learn/master?filepath=examples%2Fwater-monitor%2FWaterMonitorWorkflow.ipynb))  and get the following error on trying to run code cell 28:

```
result = workflow.execute({input_task:{'bbox':dam_bbox, 'time_interval':time_interval},
                          })

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-643ac18faa0d> in <module>()
----> 1 result = workflow.execute({input_task:{'bbox':dam_bbox, 'time_interval':time_interval},
      2                           })

/srv/conda/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in execute(self, input_args, monitor)
    165                 raise ValueError('Invalid input argument {}, should be an instance of EOTask'.format(task))
    166 
--> 167         _, intermediate_results = self._execute_tasks(input_args=input_args, out_degs=out_degs, monitor=monitor)
    168 
    169         return WorkflowResults(intermediate_results)

/srv/conda/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in _execute_tasks(self, input_args, out_degs, monitor)
    188                                         input_args=input_args,
    189                                         intermediate_results=intermediate_results,
--> 190                                         monitor=monitor)
    191 
    192             intermediate_results[dep] = result

/srv/conda/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in _execute_task(self, dependency, input_args, intermediate_results, monitor)
    215         inputs = tuple(intermediate_results[self.uuid_dict[input_task.uuid]] for input_task in dependency.inputs)
    216         LOGGER.debug("Computing %s(*%s, **%s)", str(task), str(inputs), str(kw_inputs))
--> 217         return task(*inputs, **kw_inputs, monitor=monitor)
    218 
    219     def _relax_dependencies(self, *, dependency, out_degrees, intermediate_results):

/srv/conda/lib/python3.6/site-packages/eolearn/core/eotask.py in __call__(self, monitor, *eopatches, **kwargs)
     47             return self.execute_and_monitor(*eopatches, **kwargs)
     48 
---> 49         return self.execute(*eopatches, **kwargs)
     50 
     51     @staticmethod

/srv/conda/lib/python3.6/site-packages/eolearn/io/sentinelhub_service.py in execute(self, eopatch, bbox, time_interval)
    197         request_params, service_type = self._prepare_request_data(eopatch, bbox, time_interval)
    198         request = {ServiceType.WMS: WmsRequest,
--> 199                    ServiceType.WCS: WcsRequest}[service_type](**request_params)
    200 
    201         request_dates = request.get_dates()

/srv/conda/lib/python3.6/site-packages/sentinelhub/data_request.py in __init__(self, resx, resy, **kwargs)
    469     """
    470     def __init__(self, *, resx='10m', resy='10m', **kwargs):
--> 471         super().__init__(service_type=ServiceType.WCS, size_x=resx, size_y=resy, **kwargs)
    472 
    473 

/srv/conda/lib/python3.6/site-packages/sentinelhub/data_request.py in __init__(self, layer, bbox, time, service_type, data_source, size_x, size_y, maxcc, image_format, instance_id, custom_url_params, time_difference, **kwargs)
    304         self.wfs_iterator = None
    305 
--> 306         super().__init__(**kwargs)
    307 
    308     def _check_custom_url_parameters(self):

/srv/conda/lib/python3.6/site-packages/sentinelhub/data_request.py in __init__(self, data_folder)
     39         self.download_list = []
     40         self.folder_list = []
---> 41         self._create_request()
     42 
     43     @abstractmethod

/srv/conda/lib/python3.6/site-packages/sentinelhub/data_request.py in _create_request(self)
    321         acceptable cloud coverage.
    322         """
--> 323         ogc_service = OgcImageService(instance_id=self.instance_id)
    324         self.download_list = ogc_service.get_request(self)
    325         self.wfs_iterator = ogc_service.get_wfs_iterator()

/srv/conda/lib/python3.6/site-packages/sentinelhub/ogc.py in __init__(self, **kwargs)
     97     """
     98     def __init__(self, **kwargs):
---> 99         super().__init__(**kwargs)
    100 
    101         self.wfs_iterator = None

/srv/conda/lib/python3.6/site-packages/sentinelhub/ogc.py in __init__(self, base_url, instance_id)
     36 
     37         if not self.instance_id:
---> 38             raise ValueError('Instance ID is not set. '
     39                              'Set it either in request initialization or in configuration file. '
     40                              'Check http://sentinelhub-py.readthedocs.io/en/latest/configure.html for more info.')

ValueError: Instance ID is not set. Set it either in request initialization or in configuration file. Check http://sentinelhub-py.readthedocs.io/en/latest/configure.html for more info.
```

Is there some config info needs setting anywhere?

**Comment by azupanc** [comment]
Do you have a Sentinel Hub account? If yes, then you can add your instance id to the  sentinelhub python package configuration as described here https://sentinelhub-py.readthedocs.io/en/latest/configure.html or set it directly as an argument in the initialization of the `S2L1CWCSInput` task in input cell 6. 

If you don't have a  Sentinel Hub account yet, then you'll have to create (free trail is sufficient) one at   https://sentinel-hub.com.

**Comment by psychemedia** [comment]
Hmmm.. it looks from the docs - https://sentinelhub-py.readthedocs.io/en/latest/configure.html - like AWS credentials are also required (*Requester pays* storage?)

Not possible for me to create and run an open teaching related demo then?

**Comment by AleksMat** [comment]
AWS credentials are only required if you would be downloading entire Sentinel-2 tiles from AWS. But `eo-learn` currently only uses that part of `sentinelhub` package which downloads data from Sentinel Hub services. Therefore you don't have to set AWS credentials.

**Comment by azupanc** [comment]
If you're not going to download ESA tiles from AWS, then you don't need AWS credentials. And I'm almost certain that you don't plan to do this, so you're fine. These configuration settings are just placeholders for those who download tiles from AWS.

BTW, the fact that you're doing an open teaching related demo is very interesting. Would you mind to share more? Any resources already available online?

**Comment by psychemedia** [comment]
Ok, thanks, I'm doing something wrong in just creating a new Sentinel Hub instance them (I tried all the default options) trying to get the above linked demo notebook to run. I guess I need to go and read some docs...

**Comment by batic** [comment]
Hi, 

In the configurator, create an instance based on 'Python Scripts Template'. That one has all the layers we use in our examples.

**Comment by psychemedia** [comment]
@batic Thanks... tried that.

First run, with credentials set via `instance_id` parameter in code cell 6 gives me a 'no instance ID' error in the `result = workflow.exectute()` line. Prefixing that with `! sentinelhub.config --instance_id MYINSTANCE_ID` crashes the Binder kernel. I tried reducing the date window to see if it helped, but it doesn't seem to.

**Comment by batic** [comment]
Just to make sure: you've picked the instance_id from the instance you've created from 'Python Scripts Template' and added it to cell 6?

**Comment by azupanc** [comment]
Hi Tony, the `instance_id` argument has to be specified in all eo-learn tasks that download data from Sentinel Hub. In this particular example these tasks are:

```python
input_task = S2L1CWCSInput('TRUE-COLOR-S2-L1C', resx='20m', resy='20m', maxcc=0.5,instance_id=None)
add_ndwi = S2L1CWCSInput('NDWI',instance_id=None)
cloud_det = AddCloudMaskTask(cloud_classifier, 'BANDS-S2CLOUDLESS', cm_size_y='160m',cm_size_x='160m',cmask_feature='CLM', cprobs_feature='CLP', instance_id=None)
```

Can you set in your notebook `None` with your instance id in initialization of the above three tasks and run it again? I hope this will solve your issue (at least it works for me).

Thanks for sharing your teaching plans. One of the most important reasons why we've decided to open source the eo-learn was to enable anyone with some programming knowledge (and none related to remote sensing) to be able to start extracting value out of satellite imagery. Your efforts are therefore very much appreciated.

**Comment by psychemedia** [comment]
Ah, okay.. thanks...

It would probably make sense in the notebook to add:

`INSTANCE_ID = None`

in a cell near the top of the notebook and then `instance_id=INSTANCE_ID` elsewhere.

Trying again, it ran longer but kept killing the notebook kernel on MyBinder when running the cell:

`result = workflow.execute({input_task:{'bbox':dam_bbox, 'time_interval':time_interval},})`

(Not sure if it works on pangeo or GESIS binder). I tried to reduce the `time_interval` in the preceding cell but it still bombed out for me?

**Comment by DevleenaBhattacharjee** [comment]
Many thanks ! I have been fighting the strange error since yesterday. 
As psychemedia said, can we have this as a starting note for first timers like myself please ?

**Comment by devisperessutti** [comment]
We've added a [`eo-learn-workshop` repo](https://github.com/sentinel-hub/eo-learn-workshop) where everyone can test out `eo-learn` in a Binder environment. There, you can also find clear instructions on how to set up your Sentinel-Hub account.

**Comment by AleksMat** [comment]
Hi @tushar-17-00,

I can't say for sure but my guess would be that your instance of `input_task` is not the same as the one you put into your `workflow` instance. Because of that `time_interval` parameter wouldn't get passed to the correct input task.

Could you try to restart your notebook and run it again? If that doesn't work, please send us some more context to reproduce this issue.

**Comment by Dev-Gaju** [comment]
I already set instance_id="" from my sentinel Hub account but this problem, not solve yet.
Any suggession ? Is there any way to set sentinelHub Id in Jupyter Notebook?


ValueError: During execution of task SentinelHubInputTask: Instance ID is not set. Set it either in request initialization or in configuration file. Check http://sentinelhub-py.readthedocs.io/en/latest/configure.html for more info.
