### ISSUE TITLE
Rasterio 1.2.4. Support

### ISSUE THREAD

**Issue by CChisuwo** [sentinel-hub/eo-learn#310]
I have once installed and used EO-learn using the suggested windows installation in the EO-learn documentation without any issues. However, upon migrating to python version 3.9.5.  and installing  the corresponding libraries including rasterio 1.2.4. using their .whl files I have been unable to complete the EO-learn as it requires rasterio <=1.8.

Are there plans or current development to support the recent version of rasterio in the EO-learn pipeline coming any time soon?

**Comment by AleksMat** [comment]
Hi @CChisuwo,

`rasterio` `1.2` introduced a few code-breaking changes. Reviewing the changes and adding support for the new `rasterio` versions in `eo-learn` is on our todo list but so far we haven't yet had the time for it. Therefore, for now `eo-learn` still works only for `rasterio <= 1.1.8`.

We would also be happy to accept any pull requests regarding this.

**Comment by zigaLuksic** [comment]
There is an issue with the GDAL (incorrect raster to polygon transformation) used by rasterio versions 1.2 - 1.2.6, however in version 1.2.7 they upgraded to a newer GDAL version. We therefore changed the requirement from `<=1.8` to `>=1.2.7`
