### ISSUE TITLE
[FEAT] Update the LULC blogpost according to the changes in the LULC notebook

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/eo-learn#311]
**What is the problem? Please describe.**

The notebook and the blog posts should be synced

**Comment by zigaLuksic** [comment]
@mlubej what is the progress on this? :)

**Comment by mlubej** [comment]
No update, didn't see I was assigned. It's a good task for someone new as well, so I'd prefer to unassign myself and let someone else take over.

**Comment by mlubej** [comment]
meh.. honestly I don't know if this still makes sense or not.. the blogpost is old anyway, the logic is there, the notebook was updated in the mean time, perhaps it doesn't make sense. I'd prefer to close this.
