### ISSUE TITLE
[HELP] DownloadFailedException: During execution of task AddGeopediaVectorFeature

### ISSUE THREAD

**Issue by Asnaebeya** [sentinel-hub/eo-learn#314]
Hi,

I am quite new to the EO space, I'm working off an example notebook called "CropTypeClassification_Workflow" that is no longer updated, so I'm encountering this issue with 
<img width="1219" alt="Screen Shot 2564-07-20 at 11 36 52" src="https://user-images.githubusercontent.com/55454893/126262799-f33bbb12-2376-469d-93d1-74cee29425cb.png">

It shows this error:

> DownloadFailedException: During execution of task AddGeopediaVectorFeature: Failed to download from:
> http://www.geopedia.world/rest/data/v2/search/tables/2647/features?offset=1000&limit=1000
> with HTTPError:
> 405 Client Error: Method Not Allowed for url: https://www.geopedia.world/rest/data/v2/search/tables/2647/features?offset=1000&limit=1000
> Server response: "No resource method found for GET, return 405 with Allow header"

I look into the code of AddGeopediaVectorFeature and it seems to fail from the function provided by sentinel-hub:
`GeopediaFeatureIterator`
https://sentinelhub-py.readthedocs.io/en/latest/geopedia.html

<img width="770" alt="Screen Shot 2564-07-20 at 11 41 14" src="https://user-images.githubusercontent.com/55454893/126263151-fa60932a-138a-4638-ac7a-21168f3071aa.png">

This there a way around this ?

**Comment by AleksMat** [comment]
Duplication of [this forum issue](https://forum.sentinel-hub.com/t/croptypeclassification-example-error-downloadfailedexception-during-execution-of-task-addgeopediavectorfeature/4117). We are working to fix it.
