### ISSUE TITLE
Importfromtiff and use NormalizedDifferenceIndexTask

### ISSUE THREAD

**Issue by nagatho** [sentinel-hub/eo-learn#315]
Hi,
I am trying to write a code for get data from tiff files and then calculate NDVI, NDBI and NDWI using NormalizedDifferenceIndexTask. But I can't give the data in to this NormalizedDifferenceIndexTask function.
I am new to this area and don't know how use this function correctly.
 

**code**
folder='/content/drive/MyDrive/GEE Data'
input=ImportFromTiff((FeatureType.DATA,'bands'),folder)
result = input.execute(filename='eopart_raw.tif')
result[FeatureType.DATA]['ndvi']=np.zeros((1,1,1,1))
result[FeatureType.DATA]['ndwi']=np.zeros((1,1,1,1))
result[FeatureType.DATA]['ndbi']=np.zeros((1,1,1,1))

ndvi=NormalizedDifferenceIndexTask(result.data['bands'],result[FeatureType.DATA]['ndvi'],
                              result.data['bands'][:,:,:,3], result.data['bands'][:,:,:,2])

**Comment by AleksMat** [comment]
Hi @nagatho,

An example on how to use `NormalizedDifferenceIndexTask` is in [this documentation notebook](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html#Define-the-workflow-tasks).

**Comment by nagatho** [comment]
Thanks for the reply.
I was following this example.
But the problem is now I am trying to get an image from my local hard drive.
By using the importfromtiff function.

So I want to know how give this request data to the NormalizedDifferenceIndex
task.

Did you get what I am saying?

best regard,

**Comment by AleksMat** [comment]
From those examples you can see that `NormalizedDifferenceIndexTask` has to be initialized with information about which features will be used and produced, e.g.:

```python
ndvi_task = NormalizedDifferenceIndexTask(
    (FeatureType.DATA, 'BANDS'), # Input feature
    (FeatureType.DATA, 'NDVI'),  # Output feature
    7, # 8th band in input feature, which is probably B08
    3  # 4th band in input feature, which is probably B04
)
```

Once you have that you can apply the task on an `EOPatch` holding actual data:

```python
ndvi_task.execute(result)  # if result is your EOPatch obtained from ImportFromTiff task
```

In the code you posted, you are trying to initialize the task with the data itself, which is not how `eo-learn` works.

**Comment by nagatho** [comment]
Thank you.
finally it is working.

*code *
folder='where_data_are_saved'
input=ImportFromTiff((FeatureType.DATA,'BANDS'),folder) 
result = input.execute(filename='eopart_raw.tif') 

ndvi_task = NormalizedDifferenceIndexTask((FeatureType.DATA, 'BANDS'), # Input feature
    (FeatureType.DATA, 'NDVI'),  # Output feature
    (3,2))  # 4th band in input feature, which is probably B04  # 8th band in input feature, which is probably B08  
    
ndvi_task.execute(result)
