### ISSUE TITLE
Different numbers of samples for Sentinel-1 

### ISSUE THREAD

**Issue by GalacticF** [sentinel-hub/eo-learn#32]
Different numbers of samples for Sentinel-1 

```
key = 'TRUE-COLOR-S1-IW'
input_task = S1IWWCSInput(key, resx='10m', resy='10m', instance_id=INSTANCE_ID, maxcc=0.8)
workflow = LinearWorkflow(input_task)
time_interval = ['2010-01-01','2018-12-31']
bbox = BBox(bbox=[ 150.6450033,-32.4219569,150.6583071,-32.4383657], crs=CRS.WGS84)
results = workflow.execute({input_task:{'bbox':bbox, 'time_interval':time_interval}})
```

For this request I got 41 result for area of bbox since 2017, but in eo_browser available results from 2014 (126 samples). it there any way to got all results for this period of time (2014-2017) from eo_learn package?

**Comment by batic** [comment]
At the moment the oldest S-1 data on AWS is from mid 2017, while the data on eo-cloud (used on EO-Browser) goes back to 2014. This would require access to our prototype system on eo-cloud, send us an e-mail about it to info@sentinel-hub.com.

Then you would enable access to eo-cloud data by fixing the base url in the config.json (in sentinelhub-py)

We have an example on how to do that on our "todo" list.

**Comment by GalacticF** [comment]
Hi, I've got acces, but with new access I still cannot get sentinel-1 data.
I've tried to connect to new instance to get Sentinel-1 results but using this code I got "No value present" error.
Is the any way to use new instance to connect via python?
I've tried both change INSTANCE_ID in code and in config.json,  but it doesn't works.

```
from eolearn.io.sentinelhub_service import S1IWWCSInput

INSTANCE_ID =  '2a10eb2a...'

key = 'TRUECOLOR'
input_task = S1IWWCSInput(key, resx='10m', resy='10m', instance_id=INSTANCE_ID)

workflow = LinearWorkflow(input_task)
time_interval = ['2018-01-01','2018-12-31']
from sentinelhub import WebFeatureService, BBox, CRS, DataSource
bbox = BBox(bbox=[ 150.6450033,-32.4219569,150.6583071,-32.4383657], crs=CRS.WGS84)

results = workflow.execute({input_task:{'bbox':bbox, 'time_interval':time_interval}})
```

**Comment by AleksMat** [comment]
Hi @GalacticF,

`eo-learn` package uses `sentinelhub` Python package for downloading data. In order to download data from EOCloud you also have to change base url in package's configuration file. Please check this [forum post](https://forum.sentinel-hub.com/t/sentinel-1-and-sentinel-2-images-are-not-superimposed/311/7) for further explanation.

We are also planning to prepare some examples about this in documentation.

**Comment by GalacticF** [comment]
It works, thank you!
