### ISSUE TITLE
[BUG] incompatibility of eo-learn-io with numpy 1.19

### ISSUE THREAD

**Issue by zhaoyutim** [sentinel-hub/eo-learn#335]
**Describe the bug**

NOTE: Remove any confidential information, such as Sentinel Hub credentials!

**To Reproduce**

1. when the numpy version in the local environment is below 1.20, it would report error.

**Expected behavior**

**Environment**

Details of the python environment
Python 3,7

**Stack trace or screenshots**

**Desktop (please complete the following information):**

**Additional context**
Add dependencies to numpy >= 1.20 would help

**Comment by AleksMat** [comment]
Hi @zhaoyutim,

Thank you for reporting this. A requirement `numpy>=1.20` would certainly be good.

However, this might not be the end of the `numpy` version problems. It seems that newer versions of `numba` package, which is a dependency of `eo-learn-features`, downgrade `numpy` version.

We'll have a look to see how to best limit the versions of dependencies.

**Comment by AleksMat** [comment]
The new version of `numba` now works with `numpy<1.22`. The new version `eo-learn` `1.0` also handles that in case `numba` is not installed imports from `eolearn.features` will still work.
