### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by seanfight** [sentinel-hub/eo-learn#342]
**Resources**
# TASK TO LOAD EXISTING EOPATCH
load = LoadTask(patch_path)

# TASK TO ADD SENTINEL 2 LEVEL 2A DATA
# Here also a simple filter of cloudy scenes is done. A detailed cloud cover 
# detection is performed within the next steps

# Using SH we will download the following data:
# * L2A bands: B02, B03, B04, B05, B06, B07, B08, B8A, B11, and B12
# * sen2cor's scene classification: SCL
# * s2cloudless' cloud mask: CLM
band_names = ['B02','B03','B04','B05','B06','B07','B08','B8A','B11','B12']
add_l2a = SentinelHubInputTask(
    bands_feature=(FeatureType.DATA, 'MY-S2-L2A-BANDS'),
    bands = band_names,
    resolution=10,
    maxcc=maxcloud,
    time_difference=timedelta(minutes=120),
    data_collection=DataCollection.SENTINEL2_L1C,
    additional_data=[(FeatureType.MASK, 'dataMask', 'IS_DATA'),
                     (FeatureType.MASK, 'SCL'),
                     (FeatureType.MASK, 'CLM')],
    config=config,
    max_threads=5
)

# create valid data masks
scl_valid_classes = [2, 4, 5, 6, 7]

# TASKs FOR ADDING L2A and L1C VALID DATA MASKS
# convert cloudmask to validmask
add_clm_valid =MapFeatureTask((FeatureType.MASK, 'CLM'),
                             (FeatureType.MASK, 'CLM_VALID'),
                             np.logical_not)
# combine IS_DATA and CLM_VALID
add_l1c_valmask = ZipFeatureTask({FeatureType.MASK: ['IS_DATA', 'CLM_VALID']}, 
                            (FeatureType.MASK, 'L1C_VALID'),
                            np.logical_and)
# combine IS_DATA and SCL (using an erosion radius of 6 and a dilation radius of 22 pixel for SCL classes)
add_l2a_valmask = AddValidDataMaskTask(Sen2CorValidData(scl_valid_classes, 6, 22), 'L2A_VALID')
# combine all validmasks
add_valmask = ZipFeatureTask({FeatureType.MASK: ['L1C_VALID', 'L2A_VALID']}, 
                            (FeatureType.MASK, 'VALID_DATA'),
                            np.logical_and)

# TASK TO FILTER OUT SCENES INCLUDING TOO MANY UNVALID PIXEL
# keep frames with > x % valid coverage
valid_data_predicate = ValidDataFractionPredicate(datafrac)
filter_task = SimpleFilterTask((FeatureType.MASK, 'VALID_DATA'), valid_data_predicate)

# TASK FOR CALCULATING INDICES
# NDVI = Normalized Difference Vegetation Index
# NDWI = Normalized Difference Water Index
# NORM = Euclidean Norm
ndvi = NormalizedDifferenceIndexTask((FeatureType.DATA, 'MY-S2-L2A-BANDS'), 
                                     (FeatureType.DATA, 'NDVI'),
                                     [6, 2])
ndwi = NormalizedDifferenceIndexTask((FeatureType.DATA, 'MY-S2-L2A-BANDS'), 
                                     (FeatureType.DATA, 'NDWI'),
                                     [1, 6])
norm = EuclideanNormTask((FeatureType.DATA, 'MY-S2-L2A-BANDS'), (FeatureType.DATA, 'NORM'))

# TASK FOR SAVING TO OUTPUT
save = SaveTask(patch_path, compress_level=1, overwrite_permission=OverwritePermission.OVERWRITE_PATCH)

workflow = LinearWorkflow(load, 
                          add_l2a, 
                          add_clm_valid, 
                          add_l1c_valmask, 
                          add_l2a_valmask, 
                          add_valmask, 
                          filter_task, 
                          ndvi, 
                          ndwi, 
                          norm, 
                          save)

**Question**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14608/722268800.py in <module>
     22                      (FeatureType.MASK, 'CLM')],
     23     config=config,
---> 24     max_threads=5
     25 )
     26 

~\anaconda3\envs\eolearn\lib\site-packages\eolearn\io\sentinelhub_process.py in __init__(self, data_collection, size, resolution, bands_feature, bands, additional_data, evalscript, maxcc, time_difference, cache_folder, max_threads, config, bands_dtype, single_scene, mosaicking_order, aux_request_args, data_source)
    430             if not bands:
    431                 bands = self.data_collection.bands
--> 432             self._add_request_bands(self.requested_bands, bands)
    433 
    434         if additional_data is not None:

~\anaconda3\envs\eolearn\lib\site-packages\eolearn\io\sentinelhub_process.py in _add_request_bands(self, request_dict, added_bands)
    440     def _add_request_bands(self, request_dict, added_bands):
    441         handfixed_collections = [
--> 442             DataCollection.LANDSAT_TM_L1, DataCollection.LANDSAT_TM_L2,
    443             DataCollection.LANDSAT_ETM_L1, DataCollection.LANDSAT_ETM_L2,
    444             DataCollection.LANDSAT_OT_L1, DataCollection.LANDSAT_OT_L2,

~\anaconda3\envs\eolearn\lib\enum.py in __getattr__(cls, name)
    352             return cls._member_map_[name]
    353         except KeyError:
--> 354             raise AttributeError(name) from None
    355 
    356     def __getitem__(cls, name):

AttributeError: LANDSAT_TM_L1

**Additional context**

i just run the sample of CropTypeClassification_Workflow. I don't know what's wrong with this

**Comment by zigaLuksic** [comment]
Hi @seanfight,
does the following snippet work for you?

```python
from sentinelhub import DataCollection
 test = DataCollection.LANDSAT_TM_L1
 ```

**Comment by seanfight** [comment]
***@***.***
With this problem.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Žiga ***@***.***>
发送时间: 2021年11月12日 14:22
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [sentinel-hub/eo-learn] [HELP] (Issue #342)


Hi @seanfight<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fseanfight&data=04%7C01%7C%7Ce43b74d835174eafe0d008d9a5ad310e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637722985532643440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=H7tZqx%2BuX25Cl7ZQgGlk04ynaqUgS0u6XhBqD%2BCWsPE%3D&reserved=0>,
does the following snippet work for you?

from sentinelhub import DataCollection

 test = DataCollection.LANDSAT_TM_L1

**Comment by seanfight** [comment]
> 嗨，@seanfight，下面的片段对你有用吗？
> 
> ```python
> from sentinelhub import DataCollection
> test = DataCollection.LANDSAT_TM_L1
> ```
![image](https://user-images.githubusercontent.com/17977470/141438523-4028e281-1bf1-42e7-a3b3-00340c022733.png)

**Comment by seanfight** [comment]
@zigaLuksic

**Comment by seanfight** [comment]
@zigaLuksic 
![image](https://user-images.githubusercontent.com/17977470/141440216-961afa93-c9bf-494b-92d8-3cf739874629.png)

**Comment by zigaLuksic** [comment]
Judging by the stack trace you are using eo-learn 0.10.0, and since `LANDSAT_TM_L1` is not yet present in your `sentinelhub` you are using some version before 3.4.0 (where the update was done).

**Comment by zigaLuksic** [comment]
It seems like you are using anaconda, and currently there is a versions clash on condaforge, where eo-learn has been updated but not sentinelhub-py

**Comment by zigaLuksic** [comment]
If you have the option you should upgrade `sentinelhub` to `3.4.0` (even better would be `eo-learn` `0.10.1` and `sentinelhub` `3.4.1` due to upcoming changes to the Sentinel Hub service). Otherwise downgrade your `eo-learn` to `0.9.2`, which should work with `sentinelhub` `3.3.2`.

**Comment by seanfight** [comment]
ok thank u very much

**Comment by batic** [comment]
Typically, a `pip install ...` would help in your case, even though a combination of `pip` and `conda` is not the nicest.
