### ISSUE TITLE
[HELP] Error when using ImportFromTiffTask

### ISSUE THREAD

**Issue by mesuga-reymond** [sentinel-hub/eo-learn#346]
**Resources**

Link: [ImportFromTiffTask](https://eo-learn.readthedocs.io/en/latest/eolearn.io.local_io.html?highlight=ImportFromTiffTask#eolearn.io.local_io.ImportFromTiffTask)

**Question**
I am trying to create an eopatch by importing Sentinel-1 .tiff files using ImortFromTiffTask. However, I am facing this error

![Screenshot from 2021-12-27 23-49-45](https://user-images.githubusercontent.com/74803864/147491568-dce70928-77ee-4505-9670-4c825aab02d6.png)

Can someone pls help me on this

**Comment by AleksMat** [comment]
Answered in the [forum post](https://forum.sentinel-hub.com/t/eo-learn-tutorial-documentation-for-preprocessing-sentinel-1-data/4695/7).
