### ISSUE TITLE
Handling of 503 errors

### ISSUE THREAD

**Issue by gmilcinski** [sentinel-hub/eo-learn#36]
While creating EOPatches, Sentinel Hub service returned 503 error. This happens occasionally and it would make sense to handle it somehow:
-retry the request (it happens rarely enough that you can only retry once, if the error persists, it is probably best to stop and check what is happening)
-this error stopped my process and when I restarted it, it went from start. It would make sense to save the data in some intermediate steps, otherwise there is a significant chance that process will crash every time for large areas?

**Comment by mlubej** [comment]
@AleksMat is this issue still relevant?

**Comment by AleksMat** [comment]
I think not. We are handling failed requests on sentinelhub-py level and the service is much less likely to return 503 than 2 years ago.
