### ISSUE TITLE
[HELP] ImportError: cannot import name 'S2L1CWCSInput' from 'eolearn.io'

### ISSUE THREAD

**Issue by Dwat2505** [sentinel-hub/eo-learn#361]
I am trying to run the following code. However, I am getting an import error. I have read the documentation and I can't a single reference of S2L1WCSInput. Can someone suggest how this code can be written w.r.to the current updates in eo-learn ?

```
from eolearn.io import S2L1CWCSInput, SentinelHubInputTask, S2L2AWCSInput

input_task = S2L2AWCSInput('BANDS-S2-L1C', resx='10m', resy='10m', maxcc=0.8)
add_l2a = S2L2AWCSInput(layer='BANDS-S2-L2A')
true_color  = S2L1CWCSInput('TRUE-COLOR-S2-L1C')
SENT_SAT_CLASSICATIONS = S2L2AWCSInput("SCENE_CLASSIFICATION")
```

**Comment by Dwat2505** [comment]
> Hi @Dwat2505
> 
> Please have a look at examples in the docs, e.g. [task for Sentinel-2 L1C data](https://eo-learn.readthedocs.io/en/latest/examples/io/SentinelHubIO.html#Task-for-Sentinel-2-L1C-data) or [task for L2A + SCL data](https://eo-learn.readthedocs.io/en/latest/examples/io/SentinelHubIO.html#Task-for-Sentinel-2-L2A-and-SCL-data).

The examples don't cover true_color, add_l2a and SENT_SAT_CLASSIFICATIONS.
Any suggestions for those ?

**Comment by batic** [comment]
`true_color` is either a combination of bands `B02, B03, B04` (in reverse order to get RGB image), or an evalscript (e.g. [true color](https://custom-scripts.sentinel-hub.com/sentinel-2/true_color/#), for which you'd use [SentinelHubEvalscriptTask](https://eo-learn.readthedocs.io/en/latest/eolearn.io.sentinelhub_process.html#eolearn.io.sentinelhub_process.SentinelHubEvalscriptTask), like done in the example [here](https://eo-learn.readthedocs.io/en/latest/examples/io/SentinelHubIO.html#Task-for-retrieving-NDVI-index)). Anyway, in first task ([example for L1C data](https://eo-learn.readthedocs.io/en/latest/examples/io/SentinelHubIO.html#Task-for-Sentinel-2-L1C-data)) you already have the necessary bands to construct a true-color image.

`add_l2a` is now a `SentinelHubInputTask` for L2A data, as shown in [this example](https://eo-learn.readthedocs.io/en/latest/examples/io/SentinelHubIO.html#Task-for-Sentinel-2-L2A-and-SCL-data). In the example the tasks also retrieves the scene classification bands' data.

**Comment by Dwat2505** [comment]
Alright, Thanks for the example and references.
