### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by est987** [sentinel-hub/eo-learn#38]
I'm trying to install eo-learn on a windows. After using `pip install eo-learn` , I get the following error:
![image](https://user-images.githubusercontent.com/43732852/48829357-b992d180-ed7a-11e8-8c30-d3d65c3be21b.png)
I updated GDAL to latest version, but still I get the same error.

**Comment by batic** [comment]
That is the issue related to rasterio on windows. Please have a look there. (see also issue https://github.com/sentinel-hub/eo-learn/issues/30)

**Comment by est987** [comment]
Yup, installing rasterio solved the problem.
Saw the other ticket, but was confused by different error message. In any case thanks for the quick response, closing the issue.
