### ISSUE TITLE
[BUG] Cannot import LinearWorkflow on eo-learn 0.10.0

### ISSUE THREAD

**Issue by UrielM21** [sentinel-hub/eo-learn#382]
Installing eo-learn 0.10.0 with pip caused the code to stop working on runtime when importing LinearWorkflow

### **Steps to reproduce:**

In a clean env (python 3.9) install eo-learn 0.10.0:
```bash
pip install eo-learn==0.10.0
```

Then in an interactive console this used to work but now it does not:
```python
from eolearn.core import LinearWorkflow
```
Resulting in the following error:
```bash
ImportError: cannot import name 'LinearWorkflow' from 'eolearn.core'
```

This is because the package has the following dependences:

eo-learn-coregistration>=0.10.0
eo-learn-features>=0.10.0
eo-learn-mask>=0.10.0
eo-learn-visualization>=0.10.0
eo-learn-ml-tools>=0.10.0
eo-learn-core>=0.10.0
eo-learn-io>=0.10.0
eo-learn-geometry>=0.10.0

which installs a eolearn.core version (1.0.0 as of 14-feb-2022) that eliminated the "LinearWorkflow".

### **Expected result:**
The changes in eo-learn 1.0.0 should not break previous versions.

The dependences should be changed to:
eo-learn-coregistration==0.10.0
eo-learn-features==0.10.0
eo-learn-mask==0.10.0
eo-learn-visualization==0.10.0
eo-learn-ml-tools==0.10.0
eo-learn-core==0.10.0
eo-learn-io==0.10.0
eo-learn-geometry==0.10.0

**Comment by batic** [comment]
Hi @UrielM21 

The 1.0 version introduced some code-breaking changes, as described in the [release notes](https://github.com/sentinel-hub/eo-learn/releases/tag/v1.0.0).

If your code was something along the lines of:
```python
workflow = LinearWorkflow(tasks)
```
the new code should be
```python
from eolearn.core import EOWorkflow, linearly_connect_tasks

workflow = EOWorkflow(linearly_connect_tasks(*tasks))
```

**Comment by UrielM21** [comment]
Hi Batic, thank you for your answer

I understand that the version 1.0 introduced some code-breaking changes, but what I do not understand is why a previous version (0.10.0) has a dependency on a newer version, thus breaking a working code.

Shouldn't eo-learn v0.10.0 have a dependency on a strict version of the packages (e.g. eo-learn-core==0.10.0)?

If I run the command `pip install eo-learn==0.10.0`, one would expect to have features of that version.


thank you!

**Comment by zigaLuksic** [comment]
We are working on fixing that, and a fix will probably be available next week. In the meantime you can use
```
pip install \
    "eo-learn.core==0.10.1" \
    "eo-learn.coregistration==0.10.1" \
    "eo-learn.features==0.10.1" \
    "eo-learn.geometry==0.10.1" \
    "eo-learn.io==0.10.1" \
    "eo-learn.mask==0.10.1" \
    "eo-learn.ml_tools==0.10.1" \
    "eo-learn.visualization==0.10.1"
```
or in one line `pip install "eo-learn.core==0.10.1" "eo-learn.coregistration==0.10.1" "eo-learn.features==0.10.1" "eo-learn.geometry==0.10.1" "eo-learn.io==0.10.1" "eo-learn.mask==0.10.1" "eo-learn.ml_tools==0.10.1" "eo-learn.visualization==0.10.1"` which correctly installs the `0.10.1` version

**Comment by zigaLuksic** [comment]
With the release of version `0.10.2` the command `pip install "eo-learn<1"` should also work as intended.

**Comment by torna4o** [comment]
Both ways keep giving the same error.

**Comment by zigaLuksic** [comment]
> Both ways keep giving the same error.

@torna4o Could you elaborate on precisely what does not work?
So how do you install, what packages get installed, and what command fails.

**Comment by torna4o** [comment]
> > Both ways keep giving the same error.
> 
> @torna4o Could you elaborate on precisely what does not work? So how do you install, what packages get installed, and what command fails.

Of course @zigaLuksic . I tried version 1.00, 0.11, 0.12 of eo-learn and none of them worked with "linearly_connect_tasks()" command, and produced the same error as in the question above. I tried them after creating separate conda environment for each of them. The fact is that "eolearn-core" does not have this in its source code. Hence, the tutorials with "linearly_connect_tasks()" does not work either. Fortunately, there are other versions of similar tutorials with LinearWorkflow() function working.

**Comment by zigaLuksic** [comment]
The `linearly_connect_tasks` has been introduced in eolearn-1.0.0. If you install it with pip it should work. For versions under 1.0.0 you need to use the LinearWorkflow class (deprecated in 1.0.0).

However I see you are mentioning conda, I believe we don't yet have a fully working 1.0.0 version on conda, @AleksMat ?

**Comment by torna4o** [comment]
> The `linearly_connect_tasks` has been introduced in eolearn-1.0.0. If you install it with pip it should work. For versions under 1.0.0 you need to use the LinearWorkflow class (deprecated in 1.0.0).
> 
> However I see you are mentioning conda, I believe we don't yet have a fully working 1.0.0 version on conda, @AleksMat ?

Conda is not the main issue. I am just comfortable with its virtual environments, in that way I did not need to consider any legacy sub-packages etc. remained from a different version of eo-learn, that was the reason. Otherwise, the ones with "LinearWorkflow" functions worked well in my PC now with 0.10.2 in conda created environment, but I installed rest of the packages either via pip or through windows compiled unofficial wheels.

**Comment by mlubej** [comment]
Going through old issues, not sure what was done in the end or if the issue was resolved or not. Closing this since a bunch of new versions came out in between.

@torna4o let us know if you still need any help, I'd be glad to help out.

**Comment by torna4o** [comment]
> Going through old issues, not sure what was done in the end or if the issue was resolved or not. Closing this since a bunch of new versions came out in between.
> 
> @torna4o let us know if you still need any help, I'd be glad to help out.

The issue was resolved after further cleaning my previous codes at the time considering the installed versions, thanks for checking.
