### ISSUE TITLE
[BUG] Cannot import FileFormat from eolearn.core

### ISSUE THREAD

**Issue by j-desloires** [sentinel-hub/eo-learn#383]
Dear eo-learn team, 

It seems that FileFormat has been deleted from the new updates. I was using it to EOPatch on S3 bucket. 

**Describe the bug**

ImportError: cannot import name 'FileFormat' from 'eolearn.core' 

**Expected behavior**

from eolearn.core import  FileFormat

***Details of the python environment***

eo-learn 1.0.0

**Comment by zigaLuksic** [comment]
Hi,
the `FileFormat` constants were replaced with the `MimeType` constants from the `sentinelhub-py` package. The methods are a bit different but the functionality is similar.
