### ISSUE TITLE
No module named eolearn.core in WaterMonitorWorkflow.ipynb

### ISSUE THREAD

**Issue by samakk** [sentinel-hub/eo-learn#39]
We get this error even though we did the `pip install eo-learn`

![image](https://user-images.githubusercontent.com/29838075/48935306-8b8ec800-ef07-11e8-99cc-5c2796ff3c21.png)

**Comment by Johannes-R-Schmid** [comment]
You probably need to check whether your jupyter-notebook kernel links to the correct Python environment.

**Comment by AleksMat** [comment]
I completely agree with the answer and closing the issue.
