### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by benboughton1** [sentinel-hub/eo-learn#4]
Currently the documented pip install and install_all.py break for me.

Core installs ok, then when moving on to features:

pip3 install git+https://github.com/sentinel-hub/eo-learn#subdirectory=coregistration
Collecting git+https://github.com/sentinel-hub/eo-learn#subdirectory=coregistration
  Cloning https://github.com/sentinel-hub/eo-learn to /tmp/pip-8bt4doir-build
Collecting eo-learn-core (from eo-learn-coregistration==0.1.0)
  Could not find a version that satisfies the requirement eo-learn-core (from eo-learn-coregistration==0.1.0) (from versions: )
No matching distribution found for eo-learn-core (from eo-learn-coregistration==0.1.0)

I got it working by cloning the repo and did the typical:
`python3 setup.py build`
`python3 setup.py build install`

on each module and it seems to work OK.

Ubuntu 18.04.1 fresh install with updates.

**Comment by AleksMat** [comment]
Hi Ben,

thanks for reporting the problem. At the moment we are working on preparing the first stable version of `eo-learn`. It should be done until some time next week. Then we plan to upload the package and each of the subpackages to PyPI. That will simplify the installation process.

**Comment by AleksMat** [comment]
Since the release of eo-learn version `0.3.0` last week it is possible to install the package with pip ([instructions](https://eo-learn.readthedocs.io/en/latest/install.html)). Therefore I am closing this issue.
