### ISSUE TITLE
[BUG] `FilterTimeSeriesTask` not working with multiprocessing

### ISSUE THREAD

**Issue by mcsoini** [sentinel-hub/eo-learn#446]
`from eolearn.features.feature_manipulation import FilterTimeSeriesTask` does not work with multiprocessing (e.g. `EOExecutor(...).run(workers=5)`) since the lambda function in the `super().__init__` call cannot be pickled:

```
super().__init__(FeatureType.TIMESTAMP, lambda date: start_date <= date <= end_date, filter_features)
```

This is easily solved by using a dedicated classmethod instead of  the lambda function. I can submit a PR, if desired.

I'm using eolearn 0.11. The FilterTimeSeriesTask class is unchanged in the current master.

**Comment by zigaLuksic** [comment]
Hi @mcsoini , thanks for finding the issue. A PR would be most welcome.
