### ISSUE TITLE
Error due to outdated tifffile package

### ISSUE THREAD

**Issue by daviddemeij** [sentinel-hub/eo-learn#45]
During the tutorial "Land Cover Classification with eo-learn: Part 1" we encountered the following error:

```TypeError: During execution of task S2L1CWCSInput: 'out' is an invalid keyword argument for decompress()```

This was resolved by ```conda install tifffile``` so this should probably be added as an additional dependency.

**Comment by cgohlke** [comment]
This should be fixed in [tifffile 2019.1.4](https://pypi.org/project/tifffile/)

**Comment by devisperessutti** [comment]
Thank you @cgohlke !
