### ISSUE TITLE
DoublyLogisticApproximationTask is a Asymmetric Gaussian function

### ISSUE THREAD

**Issue by j-desloires** [sentinel-hub/eo-learn#454]
Dear eo-learn development team,

After consulting this article on phenology estimation (https://www.sciencedirect.com/science/article/abs/pii/S0034425712001629), it seems that the doubly logistic function in eo-learn is rather an Asymmetric Gaussian function. 

I will do a pull request regarding the doubly logistic approximation.

Best regards,
Johann

**Comment by mlubej** [comment]
Task moved to https://github.com/sentinel-hub/eo-learn-examples/tree/main/extra-tasks/doubly_logistic_approximation

> I will do a pull request regarding the doubly logistic approximation.

If this is still relevant, please create a PR there. Thank you!
