### ISSUE TITLE
TypeError: During execution of task S2L1CWCSInput: 'out' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by ldtanh** [sentinel-hub/eo-learn#46]
I'm new to this tool, so when I took some experiments with file `/eo-learn/examples/water-monitor/WaterMonitorWorkflow.ipynb`, I got following error in Step 3:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-22-5d4dc5b66c3c> in <module>
>       2     input_task: {
>       3         'bbox': dam_bbox,
> ----> 4         'time_interval': time_interval
>       5     },
>       6 })
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in execute(self, input_args, monitor)
>     166         input_args = self.parse_input_args(input_args)
>     167 
> --> 168         _, intermediate_results = self._execute_tasks(input_args=input_args, out_degs=out_degs, monitor=monitor)
>     169 
>     170         return WorkflowResults(intermediate_results)
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in _execute_tasks(self, input_args, out_degs, monitor)
>     205                                         input_args=input_args,
>     206                                         intermediate_results=intermediate_results,
> --> 207                                         monitor=monitor)
>     208 
>     209             intermediate_results[dep] = result
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in _execute_task(self, dependency, input_args, intermediate_results, monitor)
>     238 
>     239         LOGGER.debug("Computing %s(*%s, **%s)", str(task), str(inputs), str(kw_inputs))
> --> 240         return task(*inputs, **kw_inputs, monitor=monitor)
>     241 
>     242     def _relax_dependencies(self, *, dependency, out_degrees, intermediate_results):
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eotask.py in __call__(self, monitor, *eopatches, **kwargs)
>      50         #     return self.execute_and_monitor(*eopatches, **kwargs)
>      51 
> ---> 52         return self._execute_handling(*eopatches, **kwargs)
>      53 
>      54     def execute_and_monitor(self, *eopatches, **kwargs):
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eotask.py in _execute_handling(self, *eopatches, **kwargs)
>      71             exception, traceback = caught_exception
>      72             raise type(exception)('During execution of task {}: {}'.format(self.__class__.__name__,
> ---> 73                                                                            exception)).with_traceback(traceback)
>      74 
>      75         self.private_task_config.end_time = datetime.datetime.now()
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eotask.py in _execute_handling(self, *eopatches, **kwargs)
>      64         caught_exception = None
>      65         try:
> ---> 66             return_value = self.execute(*eopatches, **kwargs)
>      67         except BaseException as exception:
>      68             caught_exception = exception, exc_info()[2]
> 
> ~/.local/lib/python3.6/site-packages/eolearn/io/sentinelhub_service.py in execute(self, eopatch, bbox, time_interval)
>     211             download_frames = get_common_timestamps(request_dates, eopatch.timestamp)
>     212 
> --> 213         images = request.get_data(raise_download_errors=self.raise_download_errors, data_filter=download_frames)
>     214 
>     215         if not self.raise_download_errors:
> 
> ~/.local/lib/python3.6/site-packages/sentinelhub/data_request.py in get_data(self, save_data, data_filter, redownload, max_threads, raise_download_errors)
>     102         """
>     103         self._preprocess_request(save_data, True)
> --> 104         data_list = self._execute_data_download(data_filter, redownload, max_threads, raise_download_errors)
>     105         return self._add_saved_data(data_list, data_filter, raise_download_errors)
>     106 
> 
> ~/.local/lib/python3.6/site-packages/sentinelhub/data_request.py in _execute_data_download(self, data_filter, redownload, max_threads, raise_download_errors)
>     157         for future in download_data(filtered_download_list, redownload=redownload, max_threads=max_threads):
>     158             try:
> --> 159                 data_list.append(future.result(timeout=SHConfig().download_timeout_seconds))
>     160             except ImageDecodingError as err:
>     161                 data_list.append(None)
> 
> /usr/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
>     423                 raise CancelledError()
>     424             elif self._state == FINISHED:
> --> 425                 return self.__get_result()
>     426 
>     427             self._condition.wait(timeout)
> 
> /usr/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
>     382     def __get_result(self):
>     383         if self._exception:
> --> 384             raise self._exception
>     385         else:
>     386             return self._result
> 
> /usr/lib/python3.6/concurrent/futures/thread.py in run(self)
>      54 
>      55         try:
> ---> 56             result = self.fn(*self.args, **self.kwargs)
>      57         except BaseException as exc:
>      58             self.future.set_exception(exc)
> 
> ~/.local/lib/python3.6/site-packages/sentinelhub/download.py in execute_download_request(request)
>     266 
>     267     if request.return_data:
> --> 268         return decode_data(response_content, request.data_type, entire_response=response)
>     269     return None
>     270 
> 
> ~/.local/lib/python3.6/site-packages/sentinelhub/download.py in decode_data(response_content, data_type, entire_response)
>     415         return json.loads(response_content.decode('utf-8'))
>     416     if MimeType.is_image_format(data_type):
> --> 417         return decode_image(response_content, data_type)
>     418     if data_type is MimeType.XML or data_type is MimeType.GML or data_type is MimeType.SAFE:
>     419         return ElementTree.fromstring(response_content)
> 
> ~/.local/lib/python3.6/site-packages/sentinelhub/download.py in decode_image(data, image_type)
>     444     bytes_data = BytesIO(data)
>     445     if image_type.is_tiff_format():
> --> 446         image = tiff.imread(bytes_data)
>     447     else:
>     448         image = np.asarray(Image.open(bytes_data))
> 
> ~/.local/lib/python3.6/site-packages/tifffile/tifffile.py in imread(files, **kwargs)
>     620     if isinstance(files, basestring) or hasattr(files, 'seek'):
>     621         with TiffFile(files, **kwargs_file) as tif:
> --> 622             return tif.asarray(**kwargs)
>     623     else:
>     624         with TiffSequence(files, **kwargs_seq) as imseq:
> 
> ~/.local/lib/python3.6/site-packages/tifffile/tifffile.py in asarray(self, key, series, out, validate, maxworkers)
>    2087         elif len(pages) == 1:
>    2088             result = pages[0].asarray(out=out, validate=validate,
> -> 2089                                       maxworkers=maxworkers)
>    2090         else:
>    2091             result = stack_pages(pages, out=out, maxworkers=maxworkers)
> 
> ~/.local/lib/python3.6/site-packages/tifffile/tifffile.py in asarray(self, out, squeeze, lock, reopen, maxsize, maxworkers, validate)
>    3854                     if lsb2msb:
>    3855                         strip = bitorder_decode(strip, out=strip)
> -> 3856                     strip = decompress(strip, out=outsize)
>    3857                     strip = unpack(strip)
>    3858                     size = min(result.size, strip.size, stripsize,
> 
> TypeError: During execution of task S2L1CWCSInput: 'out' is an invalid keyword argument for this function

Please tell me if anything more needed.

**Comment by devisperessutti** [comment]
Hello,

This is an issue with the latest version of `tifffile` which we are investigating. 

If you are using conda to install packages, uninstall the current `tifffile` version and run `conda install -c conda-forge tifffile`. If you are not using conda, uninstall the package and install the previous version by running `pip install tifffile==2018.11.28`.

This should fix the issue.

**Comment by ldtanh** [comment]
> Hello,
> 
> This is an issue with the latest version of `tifffile` which we are investigating.
> 
> If you are using conda to install packages, uninstall the current `tifffile` version and run `conda install -c conda-forge tifffile`. If you are not using conda, uninstall the package and install the previous version by running `pip install tifffile==2018.11.28`.
> 
> This should fix the issue.

Thanks. It's fixed now. Please considering to kindly add this into docs for newbie like me 👍
