### ISSUE TITLE
ValueError: During execution of task VectorToRaster: Invalid geometry object at index 0

### ISSUE THREAD

**Issue by ldtanh** [sentinel-hub/eo-learn#47]
Anyone got this error?

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-24-5d4dc5b66c3c> in <module>
>       2     input_task: {
>       3         'bbox': dam_bbox,
> ----> 4         'time_interval': time_interval
>       5     },
>       6 })
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in execute(self, input_args, monitor)
>     166         input_args = self.parse_input_args(input_args)
>     167 
> --> 168         _, intermediate_results = self._execute_tasks(input_args=input_args, out_degs=out_degs, monitor=monitor)
>     169 
>     170         return WorkflowResults(intermediate_results)
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in _execute_tasks(self, input_args, out_degs, monitor)
>     205                                         input_args=input_args,
>     206                                         intermediate_results=intermediate_results,
> --> 207                                         monitor=monitor)
>     208 
>     209             intermediate_results[dep] = result
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eoworkflow.py in _execute_task(self, dependency, input_args, intermediate_results, monitor)
>     238 
>     239         LOGGER.debug("Computing %s(*%s, **%s)", str(task), str(inputs), str(kw_inputs))
> --> 240         return task(*inputs, **kw_inputs, monitor=monitor)
>     241 
>     242     def _relax_dependencies(self, *, dependency, out_degrees, intermediate_results):
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eotask.py in __call__(self, monitor, *eopatches, **kwargs)
>      50         #     return self.execute_and_monitor(*eopatches, **kwargs)
>      51 
> ---> 52         return self._execute_handling(*eopatches, **kwargs)
>      53 
>      54     def execute_and_monitor(self, *eopatches, **kwargs):
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eotask.py in _execute_handling(self, *eopatches, **kwargs)
>      71             exception, traceback = caught_exception
>      72             raise type(exception)('During execution of task {}: {}'.format(self.__class__.__name__,
> ---> 73                                                                            exception)).with_traceback(traceback)
>      74 
>      75         self.private_task_config.end_time = datetime.datetime.now()
> 
> ~/.local/lib/python3.6/site-packages/eolearn/core/eotask.py in _execute_handling(self, *eopatches, **kwargs)
>      64         caught_exception = None
>      65         try:
> ---> 66             return_value = self.execute(*eopatches, **kwargs)
>      67         except BaseException as exception:
>      68             caught_exception = exception, exc_info()[2]
> 
> ~/.local/lib/python3.6/site-packages/eolearn/geometry/utilities.py in execute(self, eopatch)
>     132         if not bbox_map.empty:
>     133             rasterio.features.rasterize([(bbox_map.cascaded_union.buffer(0), self.raster_value)], out=raster,
> --> 134                                         transform=data_transform, dtype=self.raster_dtype)
>     135 
>     136         eopatch[self.feature_type][self.feature_name] = raster[..., np.newaxis]
> 
> ~/.local/lib/python3.6/site-packages/rasterio/env.py in wrapper(*args, **kwds)
>     371         else:
>     372             with Env.from_defaults():
> --> 373                 return f(*args, **kwds)
>     374     return wrapper
>     375 
> 
> ~/.local/lib/python3.6/site-packages/rasterio/features.py in rasterize(shapes, out_shape, fill, out, transform, all_touched, merge_alg, default_value, dtype)
>     264         if not is_valid_geom(geom):
>     265             raise ValueError(
> --> 266                 'Invalid geometry object at index {0}'.format(index)
>     267             )
>     268 
> 
> ValueError: During execution of task VectorToRaster: Invalid geometry object at index 0

I think that it happened because of my WKT file. My WKT at: https://pastebin.com/aWSUawvH

**Comment by devisperessutti** [comment]
Hi Idtanh,

Could you please share the code snippet you are trying to run, with the values of BBox and time interval, so that we can help you debug?

**Comment by AleksMat** [comment]
Closing an old issue regarding `VectorToRaster`.

The problem here was that `MultiPoint` geometrical object was given. But rasterization process only works with `Polygon` and `MultiPolygon` objects.
