### ISSUE TITLE
readthedocs links not working

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/eo-learn#497]
Some links in readme.md files aren't working, i.e. in:
- https://github.com/sentinel-hub/eo-learn/tree/master/core
- https://github.com/sentinel-hub/eo-learn/tree/master/coregistration

They lead to

<img width="822" alt="image" src="https://user-images.githubusercontent.com/37869250/200830325-cac818d5-eb85-4069-9d64-c78c5b71f8ff.png">

**Comment by zigaLuksic** [comment]
oh damn, those haven't been looked at in ages
i'm not sure we even should have READMEs there :thinking:
