### ISSUE TITLE
Land cover map example: Issue with linear interpolation on Windows 10

### ISSUE THREAD

**Issue by mickerott** [sentinel-hub/eo-learn#50]
eo-learn is a is really great python package and in particular your LULC classification example is very helpful! Thanks for the good work!

However, I often get nonsense results in the classified map. This applies to the most recent eo-learn versions 0.4.0 and 0.4.1 and [most recent LULC Notebook](https://github.com/sentinel-hub/eo-learn/blob/master/examples/land-cover-map/SI_LULC_pipeline.ipynb) - I am not entirely sure if my issue applies to previous versions, though. 

I managed to trace back the issue to the linear interpolation task; when I display one of the features in the notebook after the interpolation, I can clearly see that something does not work as it is supposed to:

![image](https://user-images.githubusercontent.com/45593441/51166953-7c901a80-18a5-11e9-87f9-1b6a82500979.png)

I am experiencing this error **only on Windows 10** (tested it on 2 different machines). 

Running the exact same Notebook works just fine on Ubuntu 18.10. Same cell displayed in Ubuntu:

![image](https://user-images.githubusercontent.com/45593441/51166966-844fbf00-18a5-11e9-94ac-f7f62d092b1b.png)

I wonder if anyone else is experiencing the same problem on Windows?

**Code snippet** (you can insert it just before "6. Model construction and training"):
```
# Load and display 7th feature (should be NDVI) for the 19th timestep
time_idx=18
timestamp = EOPatch.load(f'{path_out_sampled}eopatch_0/').timestamp[time_idx]
print(f'NDVI at {timestamp}')

img = EOPatch.load(f'{path_out_sampled}eopatch_0/').data['FEATURES'][time_idx,:,:,6]
plt.imshow(img)
```

**Comment by devisperessutti** [comment]
Hi @mickerott,

Thanks for reporting this, and running the comparison.

We are investigating this issue with the interpolation task, which was previously reported on our [Forum](https://forum.sentinel-hub.com/t/eo-learn-tutorial-example/701). The example runs on Linux and MacOS, but fails on Windows. 

We'll try to fix this as soon as time allows (we are planning to refactor the interpolation task to improve performance).

**Comment by mickerott** [comment]
Ah, I see. I did not think about checking the Sh forum regarding the issue.

Thank you for looking into the issue. I will stick to Linux then in the meantime.

**Comment by mlubej** [comment]
Dear @mickerott,

the issue was isolated and is now waiting for a merge in this [PR](https://github.com/sentinel-hub/eo-learn/pull/54).

If you want to try/test it yourself, just look a the changes, it's a really quick fix and has to do with automatic upcasting from int32 to int64 on Linux/Unix, but not on Windows. More info on the issue [here](https://github.com/numpy/numpy/issues/8433).

Thanks!

**Comment by mickerott** [comment]
Dear @mlubej ,
I tried it and it works. Thank you!
