### ISSUE TITLE
Http error

### ISSUE THREAD

**Issue by NiRajlunavat** [sentinel-hub/eo-learn#51]
Hello
Eo-learn is very nice initiative.... It's very helpful
But I'm getting error while downloading the image 
![img-20190116-wa0009](https://user-images.githubusercontent.com/37310844/51312845-39cf6d80-1a72-11e9-86d3-a7ff741d3887.jpeg)

**Comment by AleksMat** [comment]
Hi @NiRajlunavat,

the problem is that you have set your e-mail to `INSTANCE_ID` parameter. The instance ID is supposed to be a hexadecimal string in form of `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` which you get when you register to Sentinel Hub services.

Feel free to create a free trial account and test it out: [link to registration](https://services.sentinel-hub.com/oauth/subscription). 
Also please check [these instructions in documentation](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html#Requirements).

**Comment by NiRajlunavat** [comment]
Hi @AleksMat 
Thanks for your reply, i was out of station so i can't try sorry for that
can you please tell me how to get instance id

**Comment by AleksMat** [comment]
When you create Sentinel Hub account go to [Configurator](https://apps.sentinel-hub.com/configurator/), login and you will see the instance ID of your template.

For more info please check [Sentinel Hub webpage](https://www.sentinel-hub.com/develop/capabilities) or watch [introduction video](https://www.youtube.com/watch?v=tu9kFbMhGV0).
Feel free to use [Sentinel Hub forum](https://forum.sentinel-hub.com/) for similar questions.

**Comment by NiRajlunavat** [comment]
Hello @AleksMat  
Thanks for your quick reply i did it in similar manner but getting one more error now....i need your help....Thanks


DownloadFailedException: During execution of task S2L1CWCSInput: Failed to download from:
https://services.sentinel-hub.com/ogc/wcs/b54e9a3d-2bff-484d-80f2-1a3685e13d74?CRS=EPSG%3A32633&MAXCC=80.0&ShowLogo=False&COVERAGE=BANDS-S2-L1C&FORMAT=image%2Ftiff%3Bdepth%3D32f&RESY=10m&RESX=10m&REQUEST=GetCoverage&SERVICE=wcs&TIME=2017-01-01T10%3A04%3A07%2F2017-01-01T10%3A04%3A07&Transparent=True&BBOX=510157.61722214246%2C5122327.229129893%2C513489.214628833%2C5125693.036780571&EvalScript=cmV0dXJuIFtCMDIsIEIwMywgQjA0LCBCMDgsIEIxMSwgQjEyXTs%3D&VERSION=1.1.2
with HTTPError:
400 Client Error: Bad Request for url: https://services.sentinel-hub.com/ogc/wcs/b54e9a3d-2bff-484d-80f2-1a3685e13d74?CRS=EPSG%3A32633&MAXCC=80.0&ShowLogo=False&COVERAGE=BANDS-S2-L1C&FORMAT=image%2Ftiff%3Bdepth%3D32f&RESY=10m&RESX=10m&REQUEST=GetCoverage&SERVICE=wcs&TIME=2017-01-01T10%3A04%3A07%2F2017-01-01T10%3A04%3A07&Transparent=True&BBOX=510157.61722214246%2C5122327.229129893%2C513489.214628833%2C5125693.036780571&EvalScript=cmV0dXJuIFtCMDIsIEIwMywgQjA0LCBCMDgsIEIxMSwgQjEyXTs%3D&VERSION=1.1.2
Server response: "Layer BANDS-S2-L1C not found"

**Comment by AleksMat** [comment]
The layer BANDS-S2-L1C is not configured for your instance ID.

Have you read the [Requirements paragraph](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html#Requirements) at the beginning of the notebook? I think it should be clear enough that you have to create a configuration based on "Python scripts template".

**Comment by NiRajlunavat** [comment]
@AleksMat 
It's working for me now after python scripts template
Many Thanks!
closing this issue
