### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by rcbull** [sentinel-hub/eo-learn#53]
Hi

I'm try running CloudMaskTask notebook, but return bad request in download images:

See message:

**DownloadFailedException: During execution of task S2L1CWMSInput: Failed to download from:**
https://services.sentinel-hub.com/ogc/wms/MY_INSTANCE_ID?SERVICE=wms&BBOX=37.656454%2C128.689942%2C37.677434%2C128.722946&FORMAT=image%2Ftiff%3Bdepth%3D32f&CRS=EPSG%3A4326&WIDTH=252&HEIGHT=200&LAYERS=TRUE-COLOR-S2-L1C&REQUEST=GetMap&VERSION=1.3.0&TIME=2016-01-06T02%3A17%3A17%2F2016-01-06T02%3A17%3A17&MAXCC=100.0&ShowLogo=False&Transparent=True
with HTTPError:
400 Client Error: Bad Request for url: https://services.sentinel-hub.com/ogc/wms/MY_INSTANCE_ID?SERVICE=wms&BBOX=37.656454%2C128.689942%2C37.677434%2C128.722946&FORMAT=image%2Ftiff%3Bdepth%3D32f&CRS=EPSG%3A4326&WIDTH=252&HEIGHT=200&LAYERS=TRUE-COLOR-S2-L1C&REQUEST=GetMap&VERSION=1.3.0&TIME=2016-01-06T02%3A17%3A17%2F2016-01-06T02%3A17%3A17&MAXCC=100.0&ShowLogo=False&Transparent=True
**Server response: "Layer TRUE-COLOR-S2-L1C not found"**

I replaced my instance id by **MY_INSTANCE_ID**. And the instance id generated based on the template "FULL WMS Instance" in Sentinel Hub Configurations.

This is problem with instance id value? Is necessary another configurations?

**Comment by devisperessutti** [comment]
Hi,

Please use the `PYTHON-TEMPLATE` instead in the configuration utility and corresponding instance_id. The python template includes a pre-configured `TRUE-COLOR-S2-L1C` layer and other layers used in the examples.

**Comment by rcbull** [comment]
Thanks! Solved the problem

**Comment by Aveen1** [comment]
I'm having the same error, how can I resolve this?

**Comment by rebmxict** [comment]
- Go to Sentinel-Hub dashboard
- Go to Configuration Utility
- New configuration or Edit existing configuration
- Copy layer ID and use it
