### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by NourSoltani** [sentinel-hub/eo-learn#553]
**Question**

Hello, I've been following this repo [https://github.com/sentinel-hub/eo-learn-examples ]in order to do registration for sentinel2 images.. The application of registration there returns a GIF as output, and I'm looking to do obtain the geotiff (geo-referenced) of different timestamps.
Is that possible? 
 
**Additional context**
This is the eopath obejct:

EOPatch(
  data={
    BANDS: numpy.ndarray(shape=(136, 124, 90, 3), dtype=float32)
  }
  mask={
    CLM: numpy.ndarray(shape=(136, 124, 90, 1), dtype=uint8)
    IS_DATA: numpy.ndarray(shape=(136, 124, 90, 1), dtype=bool)
  }
  meta_info={
    maxcc: 0.5
    size_x: 90
    size_y: 124
    time_difference: 7200.0
    time_interval: ('2018-01-01T00:00:00', '2020-06-01T23:59:59')
  }
  bbox=BBox(((10.177620290997455, 36.71525711099706), (10.187825483373478, 36.72635603135728)), crs=CRS('4326'))
  timestamp=[datetime.datetime(2018, 1, 6, 10, 4, 51), ..., datetime.datetime(2020, 5, 28, 10, 20, 43)], length=136
)

**Comment by devisperessutti** [comment]
Hi @NourSoltani 

What you are after is the [`ExportToTiffTask`](https://eo-learn.readthedocs.io/en/latest/reference/eolearn.io.raster_io.html#eolearn.io.raster_io.ExportToTiffTask), which allows you to export each timeframe to a tiff. Read the documentation to set the arguments correctly.

Let me know if it works.

**Comment by NourSoltani** [comment]
Hi @devisperessutti
Thank you for the quick responding. I appreciate
Yes it works!! It fits well with my expectations..
There's the full code:
### Enhanced Cross-Correlation in OpenCV
params = {"MaxIters": 200}

coregister_ecc = ECCRegistrationTask(feat_bands, channel=2, params=params)

eopatch_ecc = coregister_ecc(eopatch_clean)

export_task = ExportToTiffTask((FeatureType.DATA, "BANDS"), folder="/home/Desktop/Nour/eo-learn-examples-main/coregistration/test/")
export_task.execute(eopatch_ecc,filename="temp_file_ecc.tiff")

##########Band extract###########
import rasterio

# Open the temp_file_ecc.tiff image
with rasterio.open("temp_file_ecc.tiff") as src:
    # Get the number of bands in the image
    num_bands = src.count
    # Iterate through the bands in groups of 3
    for i in range(0, num_bands, 3):
        #Read in the current group of 3 bands
        band = src.read(indexes=range(i+3, i,-1))
        # Save the current group of 3 bands as a new image
        with rasterio.open(f"image_{i//3}.tif", "w", driver="GTiff",
                           width=src.width, height=src.height,
                           count=3, dtype=band.dtype, crs=src.crs, transform=src.transform) as dst:
            dst.write(band)
            print(band)
#################################################################
#################################################################
#################################################################
But I still have a problem If you do not mind.. I need t know the date of each timestamp. Is there any method on how to figure out the chosen dates? Because he has downloaded the images this way:

roi_bbox = BBox(bbox=[31.112895, 29.957240, 31.154222, 29.987687], crs=CRS.WGS84)
time_interval = ("2018-01-01", "2020-06-01")

feat_bands = (FeatureType.DATA, "BANDS")
 
class MaxCloudCoveragePredicate:
    def __init__(self, max_cloud_coverage: float):
        self.max_cloud_coverage = max_cloud_coverage

    def __call__(self, cloud_mask: np.ndarray):
        width, height, _ = cloud_mask.shape
        cloud_coverage = np.sum(cloud_mask) / (width * height)
        return cloud_coverage <= self.max_cloud_coverage
download_task = SentinelHubInputTask(
    data_collection=DataCollection.SENTINEL2_L1C,
    bands_feature=feat_bands,
    resolution=10,
    maxcc=0.5,
    bands=["B02", "B03", "B04"],
    time_difference=datetime.timedelta(hours=2),
    additional_data=[(FeatureType.MASK, "dataMask", "IS_DATA"), (FeatureType.MASK, "CLM")],
)
filter_clouds = SimpleFilterTask((FeatureType.MASK, "CLM"), MaxCloudCoveragePredicate(max_cloud_coverage=0.05))

**Comment by NourSoltani** [comment]
Hi @devisperessutti
**Thank you for the quick responding. I appreciate
Yes it works!! It fits well with my expectations..
There's the full code:**

#################################################################
#################################################################
*** Enhanced Cross-Correlation
params = {"MaxIters": 200}
coregister_ecc = ECCRegistrationTask(feat_bands, channel=2, params=params)
eopatch_ecc = coregister_ecc(eopatch_clean)

export_task = ExportToTiffTask((FeatureType.DATA, "BANDS"), folder="/home/Desktop/Nour/eo-learn-examples-main/coregistration/test/")
export_task.execute(eopatch_ecc,filename="temp_file_ecc.tiff")

with rasterio.open("temp_file_ecc.tiff") as src:
    # Get the number of bands in the image
    num_bands = src.count
    # Iterate through the bands in groups of 3
    for i in range(0, num_bands, 3):
        #Read in the current group of 3 bands
        band = src.read(indexes=range(i+3, i,-1))
        # Save the current group of 3 bands as a new image
        with rasterio.open(f"image_{i//3}.tif", "w", driver="GTiff",
                           width=src.width, height=src.height,
                           count=3, dtype=band.dtype, crs=src.crs, transform=src.transform) as dst:
            dst.write(band)
            print(band)
#################################################################
#################################################################

**But I still have a problem If you do not mind.. I need to know the date of each timestamp. Is there any method on how to figure out the chosen dates? Because he has downloaded the images this way:**

roi_bbox = BBox(bbox=[31.112895, 29.957240, 31.154222, 29.987687], crs=CRS.WGS84)
time_interval = ("2018-01-01", "2020-06-01")

feat_bands = (FeatureType.DATA, "BANDS")
 
class MaxCloudCoveragePredicate:
    def __init__(self, max_cloud_coverage: float):
        self.max_cloud_coverage = max_cloud_coverage

    def __call__(self, cloud_mask: np.ndarray):
        width, height, _ = cloud_mask.shape
        cloud_coverage = np.sum(cloud_mask) / (width * height)
        return cloud_coverage <= self.max_cloud_coverage
download_task = SentinelHubInputTask(
    data_collection=DataCollection.SENTINEL2_L1C,
    bands_feature=feat_bands,
    resolution=10,
    maxcc=0.5,
    bands=["B02", "B03", "B04"],
    time_difference=datetime.timedelta(hours=2),
    additional_data=[(FeatureType.MASK, "dataMask", "IS_DATA"), (FeatureType.MASK, "CLM")],
)
filter_clouds = SimpleFilterTask((FeatureType.MASK, "CLM"), MaxCloudCoveragePredicate(max_cloud_coverage=0.05))

**Comment by NourSoltani** [comment]
Hi @devisperessutti
**Thank you for the quick responding. I appreciate
Yes it works!! It fits well with my expectations..
There's the full code:**

#################################################################
#################################################################
*** Enhanced Cross-Correlation
params = {"MaxIters": 200}
coregister_ecc = ECCRegistrationTask(feat_bands, channel=2, params=params)
eopatch_ecc = coregister_ecc(eopatch_clean)

export_task = ExportToTiffTask((FeatureType.DATA, "BANDS"), folder="/home/Desktop/Nour/eo-learn-examples-main/coregistration/test/")
export_task.execute(eopatch_ecc,filename="temp_file_ecc.tiff")

with rasterio.open("temp_file_ecc.tiff") as src:
# Get the number of bands in the image
num_bands = src.count
# Iterate through the bands in groups of 3
for i in range(0, num_bands, 3):
#Read in the current group of 3 bands
band = src.read(indexes=range(i+3, i,-1))
# Save the current group of 3 bands as a new image
with rasterio.open(f"image_{i//3}.tif", "w", driver="GTiff",
width=src.width, height=src.height,
count=3, dtype=band.dtype, crs=src.crs, transform=src.transform) as dst:
dst.write(band)
print(band)
#################################################################
#################################################################

**But I still have a problem If you do not mind.. I need to know the date of each timestamp. Is there any method on how to figure out the chosen dates? Because he has downloaded the images this way:**

roi_bbox = BBox(bbox=[31.112895, 29.957240, 31.154222, 29.987687], crs=CRS.WGS84)
time_interval = ("2018-01-01", "2020-06-01")

feat_bands = (FeatureType.DATA, "BANDS")

class MaxCloudCoveragePredicate:
def init(self, max_cloud_coverage: float):
self.max_cloud_coverage = max_cloud_coverage

def __call__(self, cloud_mask: np.ndarray):
    width, height, _ = cloud_mask.shape
    cloud_coverage = np.sum(cloud_mask) / (width * height)
    return cloud_coverage <= self.max_cloud_coverage
download_task = SentinelHubInputTask(
data_collection=DataCollection.SENTINEL2_L1C,
bands_feature=feat_bands,
resolution=10,
maxcc=0.5,
bands=["B02", "B03", "B04"],
time_difference=datetime.timedelta(hours=2),
additional_data=[(FeatureType.MASK, "dataMask", "IS_DATA"), (FeatureType.MASK, "CLM")],
)
filter_clouds = SimpleFilterTask((FeatureType.MASK, "CLM"), MaxCloudCoveragePredicate(max_cloud_coverage=0.05))

**Comment by devisperessutti** [comment]
The timestamps are saved in `eopatch_ecc.timestamp`, so I would suggest you actually pass a [list of names to the export task](https://eo-learn.readthedocs.io/en/latest/reference/eolearn.io.raster_io.html#eolearn.io.raster_io.ExportToTiffTask.execute) so that you will get one tiff file for each timestamp, with the filename being the timestamps. 

Something like this

```python
filenames = [f"ts.strftime('%Y%m%dT%H%M%S').tiff" for ts in eopatch_ecc.timestamp]

export_task.execute(eopatch_ecc, filename=filenames)
```

**Comment by NourSoltani** [comment]
Thank you very much!
