### ISSUE TITLE
[HELP] Error when I'm trying to run land-cover-map

### ISSUE THREAD

**Issue by fuckingsore** [sentinel-hub/eo-learn#641]
I am trying to run your [SI_LULC_pipeline.ipynb](https://github.com/sentinel-hub/eo-learn/blob/master/examples/land-cover-map/SI_LULC_pipeline.ipynb) step by step on my laptop.
I do everything written in the instructions, but at one of the stages I have an error and I don't understand what the matter is.
This block in my jupyter notebook does not start and gives an error.
```
%%time

# Time interval for the SH request
time_interval = ["2019-01-01", "2019-12-31"]

# Define additional parameters of the workflow
input_node = workflow_nodes[0]
save_node = workflow_nodes[-1]
execution_args = []
for idx, bbox in enumerate(bbox_list[patchIDs]):
    execution_args.append(
        {
            input_node: {"bbox": bbox, "time_interval": time_interval},
            save_node: {"eopatch_folder": f"eopatch_{idx}"},
        }
    )

# Execute the workflow
executor = EOExecutor(workflow, execution_args, save_logs=True)
executor.run(workers=4)

executor.make_report()

failed_ids = executor.get_failed_executions()
if failed_ids:
    raise RuntimeError(
        f"Execution failed EOPatches with IDs:\n{failed_ids}\n"
        f"For more info check report at {executor.get_report_path()}"
    )
```

Error: 

```
Process SpawnProcess-5:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\process.py", line 244, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'SentinelHubValidDataTask' on <module '__main__' (built-in)>
```

**Comment by fuckingsore** [comment]
This is my[ jupyter notebook](https://github.com/fuckingsore/diplom/blob/master/zaloga_diplom.ipynb)

**Comment by zigaLuksic** [comment]
Hi @fuckingsore 
the issue seems to be with multiprocessing. I assume you are using Windows? Windows+Jupyter+multiprocessing are a poor combination. I see two options:
1. In the `EOExecutor` set `workers=1`, this will execute the process in a single thread. Sadly it will also be slower.
2. Judging by the error it has issues with a custom class. You can try moving the definitions to a utility python file outside of the notebook, and import them from there. But that might be just one of many issues you'll face.

If you don't need to cover a huge area, then single threaded execution should work fine for you. Otherwise pick a small area, write a notebook that processes it in a single thread, just to get things to work. Then transfer the code to a regular python file , and that one you run with multiple workers to process the whole area.

**Comment by fuckingsore** [comment]
Hello, thank you for your help, I'm very grateful. Yes, I'm using windows 11 and Jupyter in Pycharm.
The first solution helped me, but another problem appeared(
What is the problem?
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File <timed exec>:24

RuntimeError: Execution failed EOPatches with IDs:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
For more info check report at D:\Lessons\Diplom\Zaloga_diplom\eoexecution-report-2023_05_08-21_57_09\report.html
`
![chrome_dukan7oNxv](https://user-images.githubusercontent.com/63148692/236920910-3a1dc77b-098e-44a3-a59c-7635b2b87f0e.png)

**Comment by zigaLuksic** [comment]
In one of the cells you are expected to download reference data (input cell 8 in the original notebook), which is a geopackage containing vector data for land-cover of a small area in SI. The EOExecutor complains that it was unable to locate such a file.

**Comment by mlubej** [comment]
Closing. @fuckingsore let us know if further help is needed otherwise.
