### ISSUE TITLE
[HELP] Perform sen2cor atmospheric correction on L1C EOPatch

### ISSUE THREAD

**Issue by lqrhy3** [sentinel-hub/eo-learn#642]
Hi! How can I perform atmospheric correction on L1C data? I need to work with data from 2016, where L2A public collection is unavailable. I see that there is `eolearn.io.sentinelhub_process.SentinelHubSen2corTask`, but as I understand it only does SCL not atmospheric correction. Is there any ways I can do the correction?

**Comment by batic** [comment]
As the documentation of the task specifies, it will

> Adds SCL (scene classification), CLD (cloud probability) or SNW (snow probability) (or their combination)
>    Sen2Cor classification results to EOPatch's MASK or DATA feature. The feature is added to MASK (SCL) or
>    DATA (CLD, SNW) feature types of EOPatch. The feature names are set to be SCL, CLD or SNW.

but do so from the (available) Sentinel-2 L2A data. If the products you are after are not available on Sentinel-Hub, then you'll have to run the Sen2COR processor yourself. In that case probably best to ask for help at https://forum.step.esa.int/c/s2tbx/6 

Good luck.

**Comment by mlubej** [comment]
Closing. @lqrhy3 let us know if further help is needed otherwise.
