### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by tscavnicar** [sentinel-hub/eo-learn#67]
Hi eo-learn team,
it would be super to have pre-built eo-learn Docker images packaging up everything user will need for both CPU as well as GPU environments. This will greatly ease the eo-learn adoption.

Any plans on this topic?

**Comment by devisperessutti** [comment]
Yes, we have these images already. 

You can find them [here](https://hub.docker.com/r/sentinelhub/queryplanet/tags) on Docker Hub.

We are planning to create new light-weight ones soon. Let us know if they fit your needs.

**Comment by tscavnicar** [comment]
Hi @devisperessutti, good to have this info. Will explore further.
