### ISSUE TITLE
ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

### ISSUE THREAD

**Issue by afolabi022** [sentinel-hub/eo-learn#676]
i wanted to visualize my workflow dependecy graph and i got this message

**Comment by afolabi022** [comment]
![oyf](https://github.com/sentinel-hub/eo-learn/assets/46848153/b2a0840a-731b-4ca2-be4e-1feb94fce61b)

**Comment by zigaLuksic** [comment]
The dependency graph requires that you have [graphviz](https://graphviz.org/) installed on your computer

**Comment by afolabi022** [comment]
thanks
