### ISSUE TITLE
CRSError in rasterio when using ExportToTiffTask

### ISSUE THREAD

**Issue by sbrisson-sudo** [sentinel-hub/eo-learn#707]
`ExportToTiffTask` fails with the `rasterio` following exception : 
```
CRSError: The WKT could not be parsed. OGR Error code 6
```
Code used to reproduce the error : 

```python
import sentinelhub
from eolearn.core import EOPatch, FeatureType
from eolearn.io import ExportToTiffTask
import numpy as np

eoptest = EOPatch()
eoptest.data_timeless['product'] = np.ones(shape=(100, 100, 1))
eoptest.bbox = sentinelhub.geometry.BBox(((706718.5069048709, 5054452.053308526), (715508.5069048709, 5064542.053308526)), crs='EPSG:25832')

export_tiff = ExportToTiffTask(feature=(FeatureType.DATA_TIMELESS, 'product'),
                           folder='/home/test.tiff',
                           date_indices=None,
                           no_data_value=255,
                           image_dtype=np.uint8)
export_tiff.execute(eoptest);
```

**Environment**

See the `conda_list.txt` and `pip_freeze.txt` files below.

**Desktop**

 - OS: Windows 10

[conda_list.txt](https://github.com/sentinel-hub/eo-learn/files/12171953/conda_list.txt)
[pip_freeze.txt](https://github.com/sentinel-hub/eo-learn/files/12171954/pip_freeze.txt)

**Comment by mlubej** [comment]
Hi @sbrisson-sudo!

can you please provide also the `test.tiff` file? You can zip it and drag&drop it here as well

**Comment by zigaLuksic** [comment]
Could you perhaps give us the full stack-trace of the error? I ran your code locally and it works for me.

**Comment by mlubej** [comment]
It also works for me, but I'm suspicious of `folder='/home/test.tiff'`, are you sure this is correct? I feel like your username might be missing.

try saving it locally `folder='./test.tiff'`

**Comment by sbrisson-sudo** [comment]
Here is te full stack trace of the error : 
[stack_trace.txt](https://github.com/sentinel-hub/eo-learn/files/12175984/stack_trace.txt)

I guess something's wrong with my environment, I've already tried to reinstall the eo-learn / sentinelhub and rasterio packages. Could you send me your python environment info so I can compare ? @mlubej @zigaLuksic 

@mlubej indeed that wasn't my first example, I took this one for replicatibility and didn't change the path. Also according to [the doc](https://eo-learn.readthedocs.io/en/latest/reference/eolearn.io.raster_io.html#eolearn.io.raster_io.ExportToTiffTask) the file name must be specified at execution. Here is the new version of the code, the error is still the same.

```python
import sentinelhub
from eolearn.core import EOPatch, FeatureType
from eolearn.io import ExportToTiffTask
import numpy as np

eoptest = EOPatch()
eoptest.data_timeless['product'] = np.ones(shape=(100, 100, 1))
eoptest.bbox = sentinelhub.geometry.BBox(((706718.5069048709, 5054452.053308526), (715508.5069048709, 5064542.053308526)), crs='EPSG:25832')

export_tiff = ExportToTiffTask(feature=(FeatureType.DATA_TIMELESS, 'product'),
                           folder='data',
                           date_indices=None,
                           no_data_value=255,
                           image_dtype=np.uint8)
export_tiff.execute(eoptest, filename = 'test.tiff')
```

**Comment by zigaLuksic** [comment]
Did a clean `pip install eo-learn` on Python 3.8 (on Ubuntu) and it worked with the code you posted above.
[environment.txt](https://github.com/sentinel-hub/eo-learn/files/12179775/environment.txt)

**Comment by sbrisson-sudo** [comment]
Ok did a cleaned fresh install on Python 3.8 and it's working (both on Ubuntu and Windows 10). 

I've must have messed up when I first tried to do it, sorry for the bothering and thanks for your support.
