### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by zhan520** [sentinel-hub/eo-learn#71]
![image](https://user-images.githubusercontent.com/12770958/53282739-15ecff00-3777-11e9-80ce-4e25ca91f89e.png)

**Comment by mlubej** [comment]
Hi @zhan520!

Thanks for providing feedback, did you do anything to the code in the notebook or did you simply just execute it? Is the problem reproducible (does it happen every time for you)? What kind of system are you using? Please give as much info that you think may be useful :)

**Comment by zhan520** [comment]
> Hi @zhan520!
> 
> Thanks for providing feedback, did you do anything to the code in the notebook or did you simply just execute it? Is the problem reproducible (does it happen every time for you)? What kind of system are you using? Please give as much info that you think may be useful :)

Thank you, I have found my mistake, I am using my own definition of .shp file ，I have improved my file and solved the problem

**Comment by mlubej** [comment]
Great! Thanks!

**Comment by pandeykiran80** [comment]
I am also getting same error in my code, how did you solve the error?
