### ISSUE TITLE
Run the prediction and export to GeoTIFF images failure

### ISSUE THREAD

**Issue by pacelu** [sentinel-hub/eo-learn#73]
before is the MAC in the local environment, MAC successfully run your case, I have successfully changed the our own data,
![image](https://user-images.githubusercontent.com/12770958/53629853-8ef1c800-3c49-11e9-990e-0b00faf20440.png)
![image](https://user-images.githubusercontent.com/12770958/53629872-94e7a900-3c49-11e9-9791-7821c657c767.png)
![image](https://user-images.githubusercontent.com/12770958/53629889-9fa23e00-3c49-11e9-9d63-3c05c5643408.png)
But now I'm going to install the project to the new environment of ubuntu,is an example of an official, ，I didn't change anything, but the project stopped in this place
![image](https://user-images.githubusercontent.com/12770958/53629952-d6785400-3c49-11e9-8ffe-0f2a98804bfd.png)
System:ubuntu18  gpu:nvidia1080ti

**Comment by zhan520** [comment]
I've been waiting for 6 hours

**Comment by mlubej** [comment]
Hi @zhan520,

we started to notice similar things happening with EOExecutor. Unfortunately we still didn't quite pinpoint what the problem is, but it has something to do with paralellising the workflow.

For now, can you confirm that it works if you do the following on a single CPU:

```
for args in tqdm(execution_args):
    workflow.execute(args)
```

Sorry for the issues.

**Comment by zhan520** [comment]
> Hi @zhan520,
> 
> we started to notice similar things happening with EOExecutor. Unfortunately we still didn't quite pinpoint what the problem is, but it has something to do with paralellising the workflow.
> 
> For now, can you confirm that it works if you do the following on a single CPU:
> 
> ```
> for args in tqdm(execution_args):
>     workflow.execute(args)
> ```
> Sorry for the issues.

Okay, I now off work, tomorrow I will try, thank you.

**Comment by zhan520** [comment]
> Hi @zhan520,
> 
> we started to notice similar things happening with EOExecutor. Unfortunately we still didn't quite pinpoint what the problem is, but it has something to do with paralellising the workflow.
> 
> For now, can you confirm that it works if you do the following on a single CPU:
> 
> ```
> for args in tqdm(execution_args):
>     workflow.execute(args)
> ```
> Sorry for the issues.

![image](https://user-images.githubusercontent.com/12770958/53874262-01451c80-403d-11e9-97b1-31c0d440a6a8.png)
Thank you, I have solved, and successfully completed their own data，

But now I want to use my server GPU training, I made the following modification, but did not succeed
![image](https://user-images.githubusercontent.com/12770958/53874468-76b0ed00-403d-11e9-9000-92addafefd9f.png)
，I need to do ？

**Comment by mlubej** [comment]
Hi @zhan520,

unfortunately, I'm not so familiar with running on GPU. Did you try to find some tutorials online? Perhaps: https://lightgbm.readthedocs.io/en/latest/GPU-Tutorial.html

**Comment by zhan520** [comment]
> Hi @zhan520,
> 
> unfortunately, I'm not so familiar with running on GPU. Did you try to find some tutorials online? Perhaps: https://lightgbm.readthedocs.io/en/latest/GPU-Tutorial.html

Thank you, I has been solved，
![image](https://user-images.githubusercontent.com/12770958/54003527-79baf300-418d-11e9-859d-f35ba09f2eca.png)
But now I want to use your own tif image data to train and predict, how should I go to convert EOPatch
![image](https://user-images.githubusercontent.com/12770958/54003703-0d8cbf00-418e-11e9-815b-b8f55c37de06.png)
![image](https://user-images.githubusercontent.com/12770958/54003711-12ea0980-418e-11e9-95f8-6015c6a5fb68.png)

**Comment by buwuyou** [comment]
> Hi @zhan520,
> 
> we started to notice similar things happening with EOExecutor. Unfortunately we still didn't quite pinpoint what the problem is, but it has something to do with paralellising the workflow.
> 
> For now, can you confirm that it works if you do the following on a single CPU:
> 
> ```
> for args in tqdm(execution_args):
>     workflow.execute(args)
> ```
> Sorry for the issues.

Hi there,
Is there an update on the parallel processing? Single CPU doesn't help much if running at a national scale.

Thanks in advance!

**Comment by devisperessutti** [comment]
This has been improved, and handles running workflows in parallel. 

The option to run either [multi-process or multi-thread is provided](https://eo-learn.readthedocs.io/en/latest/eolearn.core.eoexecution.html#eolearn.core.eoexecution.EOExecutor.run), which helps when running algorithms that already perform parallelization.
