### ISSUE TITLE
 eolearn.io import error, : DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by DevleenaBhattacharjee** [sentinel-hub/eo-learn#76]
Hello E0-Learn Team,

I am still facing this issue, can you please help.
I have installed the latest eo-learn version . But still when I do this

from eolearn.io import L8L1CWMSInput

I get the following

from eolearn.io import L8L1CWMSInput
Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\hp\Anaconda3\envs\tensorflow\lib\site-packages\eolearn\io_init_.py", line 8, in 
from .geopedia import AddGeopediaFeature
File "C:\Users\hp\Anaconda3\envs\tensorflow\lib\site-packages\eolearn\io\geopedia.py", line 7, in 
from rasterio import transform, warp
File "C:\Users\hp\Anaconda3\envs\tensorflow\lib\site-packages\rasterio_init_.py", line 23, in 
from rasterio._base import gdal_version
ImportError: DLL load failed: The specified module could not be found.

What am I doing wrong here ?

even when I am importing S2L1CWCSInput, I get the following

ImportError Traceback (most recent call last)
in 
----> 1 from eolearn.io import *

~\Anaconda3\envs\tensorflow\lib\site-packages\eolearn\io_init_.py in 
6 S2L1CWCSInput, L8L1CWMSInput, L8L1CWCSInput, S2L2AWMSInput, S2L2AWCSInput, DEMWMSInput, DEMWCSInput, 
7 AddSen2CorClassificationFeature
----> 8 from .geopedia import AddGeopediaFeature
9 from .local_io import ExportToTiff
10

~\Anaconda3\envs\tensorflow\lib\site-packages\eolearn\io\geopedia.py in 
5 import numpy as np
6 import logging
----> 7 from rasterio import transform, warp
8
9 from sentinelhub import MimeType, CustomUrlParam, CRS, GeopediaWmsRequest, transform_bbox

~\Anaconda3\envs\tensorflow\lib\site-packages\rasterio_init_.py in 
21 pass
22
---> 23 from rasterio._base import gdal_version
24 from rasterio.drivers import is_blacklisted
25 from rasterio.dtypes import (

ImportError: DLL load failed: The specified module could not be found.

**Comment by mlubej** [comment]
Similarly as in #7 try to first install with windows specific instructions

**Comment by DevleenaBhattacharjee** [comment]
This has been solved
I had to install the windows wheel instead of installing the dependent libraries by conda or pip.
Thank you very much

**Comment by salma428** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-16-8cdd6c4a7281> in <module>()
----> 1 from eolearn.io import SentinelHubInputTask, ExportToTiff
      2 from eolearn.geometry import VectorToRaster, PointSamplingTask, ErosionTask

C:\Users\HP\anaconda3\envs\MyEnvt\lib\site-packages\eolearn\io\__init__.py in <module>()
      3 """
      4 
----> 5 from .geopedia import AddGeopediaFeature
      6 from .local_io import ExportToTiff, ImportFromTiff
      7 from .sentinelhub_process import SentinelHubDemTask, SentinelHubEvalscriptTask, SentinelHubInputTask, \

C:\Users\HP\anaconda3\envs\MyEnvt\lib\site-packages\eolearn\io\geopedia.py in <module>()
     14 
     15 import numpy as np
---> 16 import rasterio.transform
     17 import rasterio.warp
     18 from sentinelhub import MimeType, CRS, GeopediaWmsRequest

C:\Users\HP\anaconda3\envs\MyEnvt\lib\site-packages\rasterio\__init__.py in <module>()
     20            pass
     21 
---> 22 from rasterio._base import gdal_version
     23 from rasterio.drivers import is_blacklisted
     24 from rasterio.dtypes import (

ImportError: DLL load failed: La procédure spécifiée est introuvable.
