### ISSUE TITLE
[FEAT]Please upgrade numpy requirement to v2

### ISSUE THREAD

**Issue by piranha32** [sentinel-hub/eo-learn#798]
A lot of packages used in remote sensing applications depends on numpy v2.x, but installation of eo-learn forces downgrade to v1.2. An example of such package is GDAL, which installs numpy2, and when used in an environment  where eo-learn downgraded numpy, crashes with non-obvious error messages.

**Comment by zigaLuksic** [comment]
The newly released version no longer has the `numpy<2` restriction.

**Comment by piranha32** [comment]
Awesome, thanks!
