### ISSUE TITLE
Land-cover-map example: Output is black.

### ISSUE THREAD

**Issue by kvigulis** [sentinel-hub/eo-learn#8]
Hello,

I've been downloading some `eopatches`, by following the 'Land Use and Land Cover (LULC) classification' example, but most of the time, depending on the location, they are just black/empty. For example, a patch with a bounding box (near Moscow):  `1862275.3544260084, 6357435.0055978615,  1881901.5999472605, 6377236.73728714` - in epsg:32633, for the time interval starting from 2018-01-01 contains 75 timestamped entries, which match the ones that come up in the 'Sentinel Hub playground'. But the true colour layer seems to be just full of zeros, for all the entries.

I've tried 'TRUE-COLOR-S2-L1C' and 'TRUE-COLOR-S2-L2A' and both seem to have this problem. I've tried multiple locations in: USA, Europe, Afrika. Several locations in UK, Latvia and Afrika, worked fine, but haven't got a single successful result within USA. The workflow settings are the same as were provided in the LULC example with Slovenia. Also I have a trial account, if that might have anything to do with it. 

Thank you

**Comment by mlubej** [comment]
Is this problem related to the other one? Did you use BBox definitions with regard to the epsg:32633 CRS in the working cases and then used the USA geojson files and corresponding BBoxes when it didn't?

**Comment by kvigulis** [comment]
Yes, this was also caused by the wrong CRS in the BBox definitions. I was keeping epsg:32633 in `1_split-AOI.ipynb` for all the GeoJson files I tried, even though the files were defined in different zones of UTM coordinate system.

Thank you @mlubej
