### ISSUE TITLE
ValueError: y contains previously unseen labels

### ISSUE THREAD

**Issue by koksalhakan** [sentinel-hub/eo-learn#82]
I  am working on another reference dataset which have similiar characteristics with your data. When i implemented to masking for no_data label, i got this following error..

ValueError: y contains previously unseen labels

This error occurs generally in case   Train data and Test data  have different categories but we mask no_data for both of datasets

**Comment by devisperessutti** [comment]
Hi @koksalhakan 

As you said, it looks like the reference train/test are different from the predicted train/test. Are you sure it's the no_data value? Can you try getting the unique labels of train/test reference and predicted labels?

Sometime a test patch might contain a label that was not seen in the training patches, generating this error.

**Comment by koksalhakan** [comment]
I think you are right. It is not about only no_data label. Probably machine predicts another class that does not exist in the reference patch because my reference data is old and land might have been changed. For example: referans patch has forest and water label but in actual fact, real area has  forest, water and wetland. Machine can detect this new wetland class.(wetland is exist in referans data but not exist in related patch) Or contrary situation, train has more label. I'll try for current reference dataset and if i get same error i'll make return about this issue again.
 Thank you... 
I wanna ask something else. How can i execute this process for all patches end-to-end as automatically ?

**Comment by mlubej** [comment]
Hi @koksalhakan!

What process are you talking about exactly? Do you mean applying the prediction to all patches?

**Comment by koksalhakan** [comment]
Hi @mlubej
Exactly. How can i do that?

**Comment by devisperessutti** [comment]
Hi @koksalhakan 

Please check the functionalities implemented in the `ml_tools` [classifier module](https://eo-learn.readthedocs.io/en/latest/eolearn.ml_tools.classifier.html#module-eolearn.ml_tools.classifier). A similar task can be created for your specific classifier, as done in the [land cover example](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html#8.-Visualization-of-the-results)
