### ISSUE TITLE
AttritbuteError: GeoDataFrame has no attribute 'lulcid'

### ISSUE THREAD

**Issue by jjpd777** [sentinel-hub/eo-learn#85]
Greetings,

I am trying to read in the land_cover_subset_small.shp file, and access the label corresponding to the lulcid. 

I am guessing that the current land_cover_subset_small.shp on the repository wasn't updated to contain the lulcid labels? Any chance you can point me in the right direction?

![Screen Shot 2019-04-04 at 7 31 04 PM](https://user-images.githubusercontent.com/29438288/55595210-cf44da00-5710-11e9-9a62-692c73f8d6f0.png)
![Screen Shot 2019-04-04 at 7 31 04 PM](https://user-images.githubusercontent.com/29438288/55595212-d1a73400-5710-11e9-906f-44d926c2d4b4.png)

**Comment by mlubej** [comment]
Hi @jjpd777!

What kind of error are you getting?

**Comment by devisperessutti** [comment]
example has been updated
