### ISSUE TITLE
order of eopatch_id 

### ISSUE THREAD

**Issue by rmtsn** [sentinel-hub/eo-learn#86]
I have carried out this process on one patch. In next step, how can i change patch_id number. Which order i can use. Because it is not like 0,1,2,3

**Comment by mlubej** [comment]
Hi @rmtsn,

are you talking about the LULC Jupyter notebook example? If not, please tell a bit more about what script you are using :)

**Comment by rmtsn** [comment]
Thank you for your reply @mlubej. Yes, i am talking about LULC example.

**Comment by mlubej** [comment]
Hi @rmtsn 

is this still relevan't? I missed your reply...

Otherwise you can define any order you like when loading the eopatches.

**Comment by mlubej** [comment]
Closing.
