### ISSUE TITLE
Land-cover-map example: sentinelhub_service.py", line 133, in _add_data     valid_mask = data[..., -1] IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by kvigulis** [sentinel-hub/eo-learn#9]
Hi,

This is related to the 'Land Use and Land Cover (LULC) classification' example - more specifically `2_eopatch-L1C.ipynb` notebook. When using a shape file of my own region, generated via `1_split-AOI.ipynb` notebook - for example this [geojson of California](https://github.com/ropensci/geojsonio/blob/master/inst/examples/california.geojson), I get the following error, when trying to execute the workflow in `2_eopatch-L1C.ipynb`: 

```
  File "/home/karlis/PythonProjects/sentinel_mining/L1C_patches.py", line 108, in <module>
    save:{'eopatch_folder':patch_name}})
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eoworkflow.py", line 165, in execute
    _, intermediate_results = self._execute_tasks(input_args=input_args, out_degs=out_degs, monitor=monitor)
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eoworkflow.py", line 188, in _execute_tasks
    monitor=monitor)
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eoworkflow.py", line 215, in _execute_task
    return task(*inputs, **kw_inputs, monitor=monitor)
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eotask.py", line 49, in __call__
    return self.execute(*eopatches, **kwargs)
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/io/sentinelhub_service.py", line 220, in execute
    self._add_data(eopatch, np.asarray(images))
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/io/sentinelhub_service.py", line 133, in _add_data
    valid_mask = data[..., -1]
IndexError: index -1 is out of bounds for axis 0 with size 0
```

In `1_split-AOI.ipynb` notebook in BBoxSplitter() function I try to set the numbers, so that the patch sizes are approximately 1000x1000 pixels, which seemed to be the case in the original example with Slovenia.

I've tried multiple locations and have so far observed this with USA (California, Texas, Nevada, Maine), also North Korea. The time interval was usually set across several months in 2018, but changing it didn't seem to affect anything, so it might be related to location or the shapefiles coming from `1_split-AOI.ipynb` notebook.

Thanks

**Comment by mlubej** [comment]
Hi @kvigulis! The problem is related to the geojson file that you use. It has coordinates, but no CRS is defined. I assume this is in the national CRS for california, which would seem to be `UTM_10N` (@AleksMat is this info saved anywhere or does one have to look for it manually?)

**Comment by kvigulis** [comment]
Thank you @mlubej. You're absolutely right. This was caused by incorrect CRS setting, when generating the shape file for bboxes of patches. Didn't know the idea behind UTM CRS.

For any beginner who stumbles upon this - GeoJson files will often use UTM CRS, which will be different depending on which zone/area of the Earth is described. So you have to set the UTM with the correct zone in `1_split-AOI.ipynb`.

**Comment by NiRajlunavat** [comment]
Hi 
I am facing the same issue....may i know where to find the CRC
Thanks

**Comment by Koesters** [comment]
> Hi
> I am facing the same issue....may i know where to find the CRC

In ArcGIS you can easily find it. 

If you go to the Coursera course from UCDavis. 
https://www.coursera.org/specializations/gis

you can get a 1 year ARCGIS license with all trimmings (pre ArcGis pro). 

Or use QGIS free. 

or use this 
https://grasswiki.osgeo.org/wiki/GRASS_Location_Wizard

the examples use epsrg: 3xxxx 

https://epsg.io/32633 is slovenia 
https://epsg.io/32630 would be the UK

will also tell you 
Linkedin says you are in India 

try http://spatialreference.org/ref/epsg/wgs-84-utm-zone-43n/

epsg projection 32643 - wgs 84 / utm zone 43n

**Comment by mlubej** [comment]
> Hi
> I am facing the same issue....may i know where to find the CRC

Sorry, my email notifications on GitHub have been acting up...

Check out the good answer from @Koesters !
