### ISSUE TITLE
Questions about Sentinel-1 images (after harmonisation with Sentinel-2)

### ISSUE THREAD

**Issue by buwuyou** [sentinel-hub/eo-learn#91]
Hello,
I'm about to integrate Sentinel-1 in the workflow. I attempt to request data via `S1IWWCSInput`  and it works smoothly. But when I requested layers of Sentinel-1 and -2 to an eopatch, the workflow fails to execute (`IndexError: During the execution of task S1IWWCSInput: index -1 is out of bounds for axis 0 with size 0`). The request can be done with S1 and S2 individually. Any idea on how to do it right?

And it was briefly mentioned in the tree cover example notebook as 
> include Sentinel-1 after harmonized with Sentinel-2

Could you give some suggestions in terms of how to do it in steps?
Many thanks in advance！

**Comment by devisperessutti** [comment]
Hello!

Different integration options could be applied depending on the use case application.

One option working with eopatches would be to create two sets of eopatches, one for S2 and one for S1 separately (ideally also splitting ascending and descending orbits). You could then apply cloud masking and temporal interpolation to S2 images to a given set of time dates. For S1 data you could apply some spatial filtering for speckle removal and apply temporal interpolation to the same time dates as S2. At this point you could merge the S1 and S2 datasets into a single eopatch (with a custom EOTask), for instance concatenating along the feature dimension.

Another option that wouldn't require interpolation would be to select the closest time date from S1 matching the S2 time dates. In this case you would have to manage properly the timestamp if you wanted to join the images into a single EOPatch.

Hope this helps.

**Comment by buwuyou** [comment]
Many thanks! It is great to know s1 and s2 should be acquired separately. Is there a Custom URL parameter for the "orbitDirection": "ASCENDING", such as the `maxcc`, when using WMS request for s1?

**Comment by mrepse** [comment]
I'm not completely sure if this is what is being asked, but you can set the orbit direction of your WMS layer in the configurator (https://apps.sentinel-hub.com/configurator/). This will only return results which go in the specified direction. It is not possible to set the direction using WMS parameters. Alternatively, if you use API requests (https://docs.sentinel-hub.com/api/latest/#/API/), these do support setting orbit direction.

**Comment by devisperessutti** [comment]
The orbit argument is available for [S1 input tasks](https://eo-learn.readthedocs.io/en/latest/eolearn.io.sentinelhub_service.html#eolearn.io.sentinelhub_service.S1IWWMSInput) as well now.
