### ISSUE TITLE
TypeError: During execution of task PointSamplingTask

### ISSUE THREAD

**Issue by mehdiselbi** [sentinel-hub/eo-learn#97]
after cell 16  :
`%%time

# Execute the workflow
# Show progress bar 
pbar = tqdm(total=len(patchIDs))
for i in range(9):
    if save_choice:
        result = workflow.execute({
            load: {'eopatch_folder': 'eopatch_{}'.format(i)},
            save: {'eopatch_folder': 'eopatch_{}'.format(i)}
        })
        del result
    else:
        result = workflow.execute({
            load: {'eopatch': eopatches[i]}
        })
        # update old patches
        eopatches[i] = result[list(result.keys())[-1]]
        del result
    pbar.update(1)`

the script raise this error

TypeError: During execution of task PointSamplingTask: __init__() got an unexpected keyword argument 'disk_radius'

**Comment by devisperessutti** [comment]
Please check the signature of the `PointSamplingTask` for the `eo-learn` version you are using. The [latest version](https://eo-learn.readthedocs.io/en/latest/eolearn.geometry.sampling.html#eolearn.geometry.sampling.PointSamplingTask) doesn't include a `disk_radius` argument
