### ISSUE TITLE
Loading local data

### ISSUE THREAD

**Issue by pmallas** [sentinel-hub/eo-learn#98]
The eolearn docs page (https://eo-learn.readthedocs.io/en/latest/) states in two places that local data can be uploaded to eolearn.

![image](https://user-images.githubusercontent.com/6051395/59447128-c9ced480-8dd0-11e9-988b-9dd7a6b082bf.png)

and 

eo-learn-io - Input/output subpackage that deals with obtaining data from Sentinel Hub services or saving and loading data locally.

However, I have not discovered a way to load local data.  Is this possible?  If so, how?

Thank you.

**Comment by drewbo** [comment]
Hi @pmallas, a [recent PR](https://github.com/sentinel-hub/eo-learn/pull/81) added the ability to read from local files via the `ImportFromTiff` task. It is not included in the latest release (0.4.2) but can be accessed by installing the package from github

**Comment by pmallas** [comment]
@drewbo - thank you for the fast response.  I will check it out.
Regards,
P

**Comment by dfnino10** [comment]
Hi. Is there a way to do this with the current version?  I would like to use local sentinel-2 level 2A images to generate the eopatch and create the masking, ndvi and the rest of the tasks. I haven’t been able to find the way to do this. Is there any example?

**Comment by mlubej** [comment]
Hi @dfnino10,

since the format of the S2 tiles changes relatively frequently and since we mainly use the Sentinel Hub services, we haven't written any mainstream code to load the S2 tiles from disk.

But since the demand for this has increased lately, perhaps we might provide an example with some disclaimer code.

In the meantime, if you happen to play around with this and write some useful code of your own, don't hesitate to contribute!

Will let you know.

**Comment by sam99dave** [comment]
> Hi @pmallas, a [recent PR](https://github.com/sentinel-hub/eo-learn/pull/81) added the ability to read from local files via the `ImportFromTiff` task. It is not included in the latest release (0.4.2) but can be accessed by installing the package from github

How can I convert the ImportFromTiff object to a polygon so that I'm able to use the UTMZoneSplitter for bbox ing?

**Comment by mlubej** [comment]
Hi @sam99dave,

When you use the import from tiff it is for importing raster images. If I understand correctly, you want to split the area, which is defined by the tiff, into smaller chunks using the splitter? Can you perhaps also provide the tiff?

**Comment by sam99dave** [comment]
> Hi @sam99dave,
> 
> When you use the import from tiff it is for importing raster images. If I understand correctly, you want to split the area, which is defined by the tiff, into smaller chunks using the splitter? Can you perhaps also provide the tiff?

Yes, the tiff file I'm working on is attached in the comment.
[L3-NC43Q06-099-067-24jan08-BAND4.zip](https://github.com/sentinel-hub/eo-learn/files/4868200/L3-NC43Q06-099-067-24jan08-BAND4.zip)

**Comment by mlubej** [comment]
Hi @sam99dave ,

thanks for the file. If you want to extract the geometry of the tile, you can do this easily in several multiple ways:

One would be using `gdalinfo` in your terminal. Part of the output that you get contains:

```
▶ gdalinfo L3-NC43Q06-099-067-24jan08-BAND4.tif 
...
Corner Coordinates:
Upper Left  (  76.2453875,   9.7546125) ( 76d14'43.40"E,  9d45'16.61"N)
Lower Left  (  76.2453875,   9.4951875) ( 76d14'43.40"E,  9d29'42.68"N)
Upper Right (  76.5048125,   9.7546125) ( 76d30'17.33"E,  9d45'16.61"N)
Lower Right (  76.5048125,   9.4951875) ( 76d30'17.33"E,  9d29'42.68"N
...
```

which you can use in python to create a bounding box.

On the other hand, you can also import the file in QGIS and extract the extent from Vector/Research Tools/Extract Layer Extent. Then you can also save and load this as a shapefile/geojson/geopackage in python.

Let me know if you have any other issues.

**Comment by sam99dave** [comment]
> Hi @sam99dave ,
> 
> thanks for the file. If you want to extract the geometry of the tile, you can do this easily in several multiple ways:
> 
> One would be using `gdalinfo` in your terminal. Part of the output that you get contains:
> 
> ```
> ▶ gdalinfo L3-NC43Q06-099-067-24jan08-BAND4.tif 
> ...
> Corner Coordinates:
> Upper Left  (  76.2453875,   9.7546125) ( 76d14'43.40"E,  9d45'16.61"N)
> Lower Left  (  76.2453875,   9.4951875) ( 76d14'43.40"E,  9d29'42.68"N)
> Upper Right (  76.5048125,   9.7546125) ( 76d30'17.33"E,  9d45'16.61"N)
> Lower Right (  76.5048125,   9.4951875) ( 76d30'17.33"E,  9d29'42.68"N
> ...
> ```
> 
> which you can use in python to create a bounding box.
> 
> On the other hand, you can also import the file in QGIS and extract the extent from Vector/Research Tools/Extract Layer Extent. Then you can also save and load this as a shapefile/geojson/geopackage in python.
> 
> Let me know if you have any other issues.

Thank you. I'll try this.

**Comment by mlubej** [comment]
Assuming it worked. Let us know otherwise.

Closing.
